- charts/secrets-store-csi-driver/templates/crd-csi-driver-registry.yaml
Make sure the CRD is installed before it is used.
> Deploy CRD first

- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- deploy/secrets-store-csi-driver.yaml
- pkg/csi-common/utils.go
- pkg/providers/azure/provider.go
- pkg/providers/vault/provider.go
- Redact client id and secret in GRPC request log
- Redact access token and client id in Azure provider pod identity scenario
- Reduce log verbosity in deployment
Fixes #53 
Example log:
```
I0906 19:58:02.943210       1 utils.go:130] GRPC request: {VolumeId:csi-ff1aba1aefda574ea47d04fecff1ff4d2724eb6d43878da6cc1f29d908283576 PublishContext:map[] StagingTargetPath: TargetPath:/var/lib/kubelet/pods/f2a9a247-47d7-4718-8b45-ab4ec531d897/volumes/kubernetes.io~csi/secrets-store-inline/mount VolumeCapability:mount:<> access_mode:<mode:SINGLE_NODE_WRITER >  Readonly:true Secrets:map[clientid:6009##### REDACTED #####f3eb clientsecret:162e##### REDACTED #####0c8c] VolumeContext:map[csi.storage.k8s.io/pod.name:nginx-secrets-store-inline-pod-identity csi.storage.k8s.io/pod.namespace:default …
```
> redact clientid and secret in logs

- README.md
- charts/secrets-store-csi-driver/values.yaml
- deploy/provider-vault.yaml
- test/bats/azure.bats
- Enable azure providers for azure e2e tests
- Update provider url 
- Bump vault provider to `0.0.2` version
> enable azure provider for e2e

- test/bats/azure.bats
`csi-secrets-store-attacher` is no longer deployed. So removing the check from azure e2e.
> remove attacher running check from e2e

- cmd/secrets-store-csi-driver/main.go
- pkg/secrets-store/nodeserver.go
- Check if mounted before unmount 
- Use results of `IsLikelyNotMount` after node publish volume is complete.
Fixes #123, #106
> check is mounted before unmount

- charts/secrets-store-csi-driver/templates/role.yaml
- charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- deploy/rbac-secretproviderclass.yaml
- deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- pkg/secrets-store/nodeserver.go
- secretProviderClass/Makefile
- secretProviderClass/PROJECT
- secretProviderClass/api/v1alpha1/groupversion_info.go
- secretProviderClass/config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- secretProviderClass/config/rbac/role.yaml
- test/bats/azure.bats
- test/bats/tests/azure_v1alpha1_secretproviderclass.yaml
- test/bats/tests/vault_v1alpha1_secretproviderclass.yaml
- test/bats/vault.bats
Fixes #112 
NOTE: will remove references of crd `secretproviderclasses.secrets-store.csi.k8s.com` after we make a new release and push a new image tag.
> Update api to x-k8s

- charts/secrets-store-csi-driver/values.yaml
- deploy/provider-azure.yaml
- deploy/provider-vault.yaml
Bump provider versions in prep for new driver release that will support driver-provider compatibility check. 
```
root@k8s-agentpool1-32372105-vmss000000:/# ./etc/kubernetes/secrets-store-csi-providers/azure/provider-azure --version
{"version":"0.0.3","buildDate":"2019-12-13-01:49","minDriverVersion":"v0.0.8"}
root@k8s-agentpool1-32372105-vmss000000:/# ./etc/kubernetes/secrets-store-csi-providers/vault/provider-vault --version
{"version":"0.0.4","buildDate":"2019-12-12-16:41","minDriverVersion":"v0.0.8"}
```
> bump provider versions

- charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- secretProviderClass/config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- test/bats/vault.bats
- Removing the `all` category as not all users will have the rbac permission to query this. 
- Removing the `secretproviderclass` category as the singular field already handles this
> Remove categories for secretproviderclasses

- Makefile
- README.md
- charts/secrets-store-csi-driver/Chart.yaml
- charts/secrets-store-csi-driver/templates/NOTES.txt
- cmd/secrets-store-csi-driver/main.go
- go.mod
- pkg/secrets-store/controllerserver.go
- pkg/secrets-store/identityserver.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/secrets-store_test.go
- secretProviderClass/PROJECT
- secretProviderClass/go.mod
- test/sanity/sanity_test.go
Since the repo move to `kubernetes-sigs` is complete, we can update the path alias to `sigs.k8s.io`.
> update repo path to sigs.k8s.io

- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- deploy/secrets-store-csi-driver.yaml
- bump `csi-node-driver-registrar` image to latest available release `v1.2.0`
/assign @ritazh
> bump csi-node-driver-registrar to v1.2.0

- deploy/secrets-store-csi-driver.yaml
liveness probe support PR was merged - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/142. Helm charts already have the changes included. Updating the deployment manifests also to include the side car now that new release has been cut with the changes.
/assign @ritazh
> add liveness probe sidecar to deploy manifest

- Makefile
- charts/secrets-store-csi-driver/templates/_helpers.tpl
- charts/secrets-store-csi-driver/templates/csidriver.yaml
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- charts/secrets-store-csi-driver/values.yaml
- deploy/secrets-store-csi-driver-windows.yaml
- deploy/secrets-store-csi-driver.yaml
- test/bats/azure.bats
- test/bats/tests/azure_v1alpha1_secretproviderclass.yaml
- test/bats/tests/nginx-pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
- test/bats/tests/nginx-pod-vault-inline-volume-secretproviderclass.yaml
- test/bats/vault.bats
- Updates makefile to add rule for windows-e2e
- Adds helm chart for windows
fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/179
> update tests for windows

- charts/secrets-store-csi-driver/templates/csidriver.yaml
`Capabilities.KubeVersion.Version` is deprecated, so switching to use `Capabilities.KubeVersion.Version` as recommended here - https://github.com/helm/helm/blob/master/pkg/chartutil/capabilities.go#L58-L61
> helm: switch to using version instead of gitversion

- README.md
- charts/secrets-store-csi-driver/README.md
fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/182, fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/115
- Moves helm install instructions to new `README` under charts/*
- Adds install instructions for windows
- Removes references to examples that are no longer in the repo
- Points to provider configuration and install steps 
- Removes references to helm2
> restructure docs and add windows instructions

- Dockerfile
- Makefile
- windows.Dockerfile
- Updates dockerfile with a builder image
- Updates base image with us.gcr.io/k8s-artifacts-prod/build-image/debian-base-amd64:v2.1.0 as minimal base (https://github.com/kubernetes/kubernetes/tree/master/build/debian-base)
- Uses docker buildx to build cross-platform images
Fixes #196 
> update base image with debian base

- charts/secrets-store-csi-driver/README.md
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- charts/secrets-store-csi-driver/values.yaml
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/utils.go
- pkg/secrets-store/utils_test.go
- Makes `kubeletDir` configurable. Default value is `/var/lib/kubelet` for Linux and `C:\var\lib\kubelet` for Windows.
- Change logic to get the podUID from target path.
Fixes #206 
> feat: allow kubelet root dir to be configurable

- Makefile
- docker/BASEIMAGE
- docker/BASEIMAGE_CORE
- docker/Dockerfile
- docker/Makefile
- docker/build.sh
- docker/cloudbuild.yaml
- docker/windows.Dockerfile
In order for the secret store CSI image to be automatically built and published to the staging registry (from which it will be promoted), the ``cloudbuild.yaml`` file has been added.
The file was added in conformance with [1].
Adds the docker folder, which contains several items:
- cloudbuild.yaml
- BASEIMAGE: the base image to use when building an image for a certain os/arch
(or os/arch/version for Windows).
- BASEIMAGE_CORE: for Windows images, from which image to copy necessary files (DLLs).
- Makefile
- build.sh: script that can build, push, and create the manifest list.
- Dockerfile: needed to build the Linux docker image. Can now accept the a
BASEIMAGE arg, which can be useful when building multi-arch images.
- windows.Dockerfile: needed to build the Windows docker image. Can now …
> Adds image automated build

- docker/cloudbuild.yaml
Sets `HOME=/root` in cloud build explicitly to make `buildx` work.
Tested using `cloud-build-local`
Fixes #
> Set HOME=/root for cloudbuild

- Makefile
- charts/secrets-store-csi-driver/README.md
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- charts/secrets-store-csi-driver/values.yaml
- deploy/secrets-store-csi-driver-windows.yaml
- deploy/secrets-store-csi-driver.yaml
- Update `nodeSelector` labels to `kubernetes.io/os`
- Make `nodeSelector` configurable in helm charts
Fixes #231 
/kind cleanup
> chore: update node selector and make it configurable

- Makefile
- test/bats/tests/vault.yaml
- test/bats/vault.bats
* Update latest tools for e2e. Install commands if it does not exist. It makes it more convenient for running locally.
* Fix wrong usage of arithmetic binary operators usage in bats it made wrong assets.
```shell
$ result=$(kubectl exec -it nginx-secrets-store-inline cat /mnt/secrets-store/foo1)
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
$ [[ "$result" -eq "hello1" ]]; echo $?
0
$ [[ "$result" -eq "hello" ]]; echo $?
0 # wrong
```
* Update latest usage of `kubectl exec` to dismiss the deprecated warning.
**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets …
> Update and fix e2e-vault

- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/utils_test.go
- pkg/version/version.go
- Uses `exec.CommandContext` when calling the provider binary. This ensures if the provider doesn't respond before the context timeout, then command times out and the process is killed. The `NodePublishVolume` will then return an error and also unmount the previously mounted `targetPath`. When `kubelet` retries the mount again with the `targetPath` for the pod, the `NodePublishVolume` will be retried as expected. 
Fixes #236 
> set context for provider binary calls

- charts/secrets-store-csi-driver/README.md
- charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- charts/secrets-store-csi-driver/values.yaml
- deploy/secrets-store-csi-driver.yaml
- Updates `livenessprobe` container version to `v2.0.0`
- Set log verbosity to 2 for `livenessprobe` container as the frequent health check logs have been set at log level 5 in `v2.0.0`
Fixes #247 
> chore: update to livenessprobe v2.0.0

- docker/cloudbuild.yaml
The windows base images are taking time to be pulled in cloud build and as result failing to complete before timeout. Increasing it to `1800s` to provide additional time for image pulls to succeed. 
Fixes #
> chore: increase cloud build timeout to 1800s

- Makefile
- docs/RELEASE.md
- manifest_staging/charts/secrets-store-csi-driver/Chart.yaml
- manifest_staging/charts/secrets-store-csi-driver/README.md
- manifest_staging/charts/secrets-store-csi-driver/templates/NOTES.txt
- manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
- manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role_binding.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/serviceaccount.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
- manifest_staging/deploy/csidriver-1.15.yaml
- manifest_staging/deploy/csidriver.yaml
- manifest_staging/deploy/rbac-secretproviderclass.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- Adds docs for release process, some helper targets to run as part of generating the helm charts and release manifests.
- Adds `manifest_staging` dir to stage deployment manifest changes required for next release. There is no charts dir here, as new flags for helm charts can be added by wrapping them in conditionals similar to [this](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml#L54-L56). The helm charts are always used to test PRs and master.
Fixes #201  …
> doc: add release doc and targets

- pkg/secrets-store/nodeserver.go
Passing through the csi.storage.k8s.io/serviceAccount.name parameter will allow plugins who need to obtain K8S SA tokens to perform
workload identity to not need to perform additional get pod K8S API calls.
See: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/29
> attributes: pass csi.storage.k8s.io/serviceAccount.name

- Makefile
- test/bats/azure.bats
- test/bats/vault.bats
- Checks if the provider pods are ready before getting the pod name
Fixes #
Prevents flakes similar to -
```
not ok 1 install azure provider
```
where the provider pod is not yet scheduled
/kind flake
> test: check pod ready status before getting name

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Introduced in a previous PR, the tolerations block should be inside the `{{- if .Values.linux/windows.enabled}}` conditional in the Daemon Set yaml; it is currently outside.
This could cause issues if the `enabled` flag of a specific OS is false, but there are tolerations defined for it.
Detected while testing with `secrets-store-csi-driver-provider-azure`
> helm: move tolerations block inside OS conditional in helm chart

- config/rbac/role.yaml
- controllers/secretproviderclasspodstatus_controller.go
- manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
- manifest_staging/deploy/rbac-secretproviderclass.yaml
- Run `make manifests` to generate rbac changes and remove permissions no longer required
Fixes #
> chore: regenerate manifests to remove unused rbac permissions

- Makefile
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- test/bats/tests/vault/vault_v1alpha1_secretproviderclass_ns.yaml
- Adds `preserveUnknownFields=false` marker for CRD generation. This is required for `kubectl explain`.
Fixes #214 
```
➜ kubectl explain secretproviderclass                                                                                              
KIND:     SecretProviderClass
VERSION:  secrets-store.csi.x-k8s.io/v1alpha1
DESCRIPTION:
SecretProviderClass is the Schema for the secretproviderclasses API
FIELDS:
apiVersion   <string>
APIVersion defines the versioned schema of this representation of an
object. Servers should convert recognized schemas …
```
> feat: add preserveUnknownFields=false marker

- manifest_staging/charts/secrets-store-csi-driver/README.md
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
This PR allows to configure all the image repositories if needed. For our container platfom only containers from private registries are allowed.
fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/255
> helm: make all images configurable

- test/bats/azure.bats
- test/bats/tests/azure/azure_v1alpha1_multiple_secretproviderclass.yaml
- test/bats/tests/azure/nginx-pod-azure-inline-volume-multiple-spc.yaml
- test/bats/tests/vault/nginx-pod-vault-inline-volume-multiple-spc.yaml
- test/bats/tests/vault/vault_v1alpha1_multiple_secretproviderclass.yaml
- test/bats/vault.bats
With the introduction of new reconciler for creating k8s secrets, multiple `SecretProviderClass` for secret objects is handled. Adding e2e tests as part of this PR to CI.
Fixes #187 
> test: add tests for multiple secret provider class

- manifest_staging/charts/secrets-store-csi-driver/README.md
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
Users can set environment variables to be set/overridden via helm chart
Fixes #246
> helm: add support for envs in helm chart

- .golangci.yml
- Makefile
`make test` never exit
Fixes #281
> chore: update golangci-lint to v1.30.0

- README.md
Test files were moved to a new subdirectory but the links were never updated, this PR updates the links to include the "vault" subdirectory and changes them to be relative.
> doc: fixing links where files were moved to a new subdirectory.

- Makefile
`az` cli has been removed from kubetest image as part of this PR - https://github.com/kubernetes/test-infra/pull/18403. Checking to see if we can remove the dependency on `az login` 
Fixes #
> ci: remove az cli req

- manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
- Updates Helm chart resources to use recommended/standard labels.  
- Prevents undesired restarts of the secrets-store-csi-driver daemonset when running `helm upgrade --install` due to changing `revision` label.
- ~~Moves SecretProviderClass CRDs to `crds` directory.  Prevents issues when installing on a cluster with pre-existing SecretProviderClass CRDS. (e.g.```Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: , name: secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition```)~~
**Which issue(s) …
> helm: chart best practices

- Makefile
- config/rbac-syncsecret/kustomization.yaml
- config/rbac-syncsecret/role.yaml
- config/rbac-syncsecret/role_binding.yaml
- config/rbac/role.yaml
- controllers/secretproviderclasspodstatus_controller.go
- controllers/syncsecret/syncsecret.go
- manifest_staging/charts/secrets-store-csi-driver/README.md
- manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret_binding.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
- manifest_staging/deploy/rbac-secretproviderclass.yaml
- manifest_staging/deploy/rbac-secretprovidersyncing.yaml
Addresses #243, allowing users to choose to not grant as many privileges to the CSI driver and help prevent against accidentally
persisting secrets to K8S's datastore which may not be appropriate in
some environments.
Fixes #243
This _only_ modifies the permissions installed, which would just lead to repeated error messages in the reconciler whenever it attempts to sync a secret. I could also change the controller to accept a flag and skip secret syncing which may lead to a better error message. Let me know what you think!
> roles: split secret sync a separate role: secretprovidersyncing-role

- test/bats/azure.bats
- test/bats/tests/azure/nginx-deployment-two-synck8s-azure.yaml
- test/bats/tests/vault/nginx-deployment-two-synck8s.yaml
- test/bats/vault.bats
- Updates test for single secret with multiple owners
- Checks when the first owner is deleted, the secret still exists and the deleted owners are removed from the `ownerReferences`
- When the last owner is deleted, the secret is subsequently deleted as part of the cascading deletion.
Fixes #
> test: update test for secret with multiple owner references

- controllers/secretproviderclasspodstatus_controller.go
- test/bats/azure.bats
- test/bats/vault.bats
This PR adds a new label to the secrets created by the `secrets-store-csi-driver`. This serves as basic plumbing for enabling filtered watches on the secrets as part of rotation reconciler. 
Fixes #
> feat: add managed label to secret created by driver

- pkg/secrets-store/mocks/stats_reporter_mock.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/stats_reporter.go
- pkg/secrets-store/utils_test.go
Adds more tests for NodePublishVolume and NodeUnpublishVolume functions
Fixes #132 
I think it would be great if it was possible to also test success scenario for NodePublishVolume. At the moment the code that executes the provider binary with args runs directly in the NodePublishVolume function, but maybe if could be factored out?
> feat: add unit tests for secrets-store pkg

- apis/v1alpha1/secretproviderclasspodstatus_types.go
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- `PodUID` field is not used in `SecretProviderClassPodStatus`
- No deprecation notice required as this field was never exposed for use
Fixes #
/kind cleanup
> chore: remove unused PodUID field in secretproviderclasspodstatus

- Makefile
- The new release for `azure` provider now only supports gRPC for communication. Updating the e2e helm install to include the provider.
Fixes #
> chore: update e2e helm install for grpc supported provider

- cmd/secrets-store-csi-driver/main.go
- Updates the default rotation poll interval to `2m`
Fixes #
/kind cleanup
> chore: update default rotation poll interval to 2m

- cmd/secrets-store-csi-driver/main.go
- config/rbac/role.yaml
- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
- manifest_staging/deploy/rbac-secretproviderclass.yaml
- pkg/k8s/pod.go
- pkg/k8s/secret.go
- pkg/k8s/secretproviderclass.go
- pkg/k8s/secretproviderclasspodstatus.go
- pkg/k8s/store_test.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/secrets-store.go
- pkg/util/secretutil/secret.go
- pkg/util/secretutil/secret_test.go
- Adds event recorder to generate events for secret creation failure/ when mounted contents are rotated
- Adds SHA check to determine if updating secret is required
- 
Fixes #307 
```bash
Normal  MountRotationComplete   8s    csi-secrets-store-rotation  successfully rotated mounted contents for spc default/azure
Normal  SecretRotationComplete  8s    csi-secrets-store-rotation  successfully rotated K8s secret foosecret
```
> feat: add event recorder for secrets creation and rotation

- pkg/rotation/reconciler.go
- pkg/secrets-store/provider_client_test.go
- provider/fake/fake_server.go
Fixes scenarios where the `nodePublishSecretRef` doesn't exist for rotation
Fixes #
> fix: marshal secrets for non node publish secret ref

- Makefile
- test/bats/gcp.bats
- test/bats/tests/gcp/gcp_v1alpha1_secretproviderclass.yaml
- test/bats/tests/gcp/nginx-pod-secrets-store-inline-volume-crd.yaml
Adds integration tests for the GCP Secret Manager plugin: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp
Fixes #
Starting with a single test case.
Changes to test-infra: https://github.com/kubernetes/test-infra/pull/19512
and uploading of a new secret (`gcp-secrets-store-cred`) to prow
> GCP plugin: integration tests

- manifest_staging/charts/secrets-store-csi-driver/values.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
The gcp plugin only works with `--grpc-supported-providers`, so adding it to the template to set by default.
> deploy: add gcp as grpcSupportedProviders by default

- .golangci.yml
- pkg/errors/errors.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/utils.go
- pkg/util/secretutil/secret.go
- test/bats/azure.bats
- test/bats/vault.bats
- Adds `gosec`, `deadcode`, `structcheck` and `varcheck` linters to golangci config.
- Switch to using sha256 as sha1 is weak
```bash
pkg/util/secretutil/secret.go:22:2: G505: Blocklisted import crypto/sha1: weak cryptographic primitive (gosec)
"crypto/sha1"
^
pkg/util/secretutil/secret.go:201:12: G401: Use of weak cryptographic primitive (gosec)
hasher := sha1.New()
```
Fixes #350 
> feat: add gosec linter and fix warnings

- test/bats/azure.bats
- test/bats/helpers.bash
- test/bats/vault.bats
- Makes tests more deterministic to reduce flakes
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/355
/kind cleanup
> test: make tests more deterministic and retries

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
Removing the lifecycle prestop commands for `node-driver-registrar`
- `node-driver-registrar` switched to using a distroless image. So shell is no longer available.
- `node-driver-registrar` cleans up the registration socket as part of shutdown - https://github.com/kubernetes-csi/node-driver-registrar/pull/61
Fixes #
/kind cleanup
> chore: remove lifecycle prestop command

- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- go.mod
- pkg/errors/errors.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/utils.go
- pkg/util/fileutil/filesystem.go
- pkg/util/fileutil/filesystem_test.go
- pkg/util/k8sutil/volume.go
- pkg/util/k8sutil/volume_test.go
Consolidated duplicate GetMountedFiles and GetPodUIDFromTargetPath as well.
> fix: validate SPCPS targetPaths match Pod UIDs

- controllers/secretproviderclasspodstatus_controller.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
Checks if the pod is terminating while inside the reconcile or rotation loop. If the pod is terminating, then return.
Fixes #
> fix: handle pod termination during reconcile

- test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
- test/bats/tests/vault/vault_v1alpha1_multiple_secretproviderclass.yaml
- test/bats/tests/vault/vault_v1alpha1_secretproviderclass.yaml
- test/bats/tests/vault/vault_v1alpha1_secretproviderclass_ns.yaml
- test/bats/vault.bats
v0.0.5 of the vault provider introduced a breaking change which the integration tests here were never updated for. This PR fixes the tests so they should pass for v0.0.6, and allow us to merge https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/pull/53 safely.
None
Apologies for the conflicts with #245 but I've tried to keep the diff to a minimum to make it easier to port over to that PR.
> Fix vault bats tests for running against v0.0.6 of the provider

- cmd/secrets-store-csi-driver/main.go
- controllers/secretproviderclasspodstatus_controller.go
- pkg/csi-common/server.go
- pkg/csi-common/utils.go
- pkg/secrets-store/secrets-store.go
- test/sanity/sanity_test.go
Cleanup missing `Close()` on the unix socket which can lead to the file persistent. This is best effort, if the process does not exist gracefully the socket file could remain.
Fixes #367
I think this is all that's missing unless I'm misunderstanding #367
The wait group on `NonBlockingGRPCServer` was never actually done. Updated `Start` to pass in a parent cancelable context so that `Start` and `Wait` _could_ finish.
> chore: best-effort cleanup socket

- controllers/secretproviderclasspodstatus_controller.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
We already check for pods in terminating state and skip them:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/9e70aa690aeb2fc8dc6bbfcf8ce6879f8b12c65b/pkg/rotation/reconciler.go#L182-L187
However, for pods generated as part of cronjob, they are set to `Completed` state but aren't garbage collected until much later based on `.spec.successfulJobsHistoryLimit` or `.spec.failedJobsHistoryLimit`. The `.status.Phase` for the completed pods are set to `Succeeded` and for failed pods it's `Failed`.
```json
// PodSucceeded means that all containers in the pod have voluntarily terminated
// with a container exit code of 0, and the system is not going to restart any of these containers.
PodSucceeded PodPhase = "Succeeded"
// PodFailed means …
```
> fix: skip pods in succeeded or failed phase

- README.md
- config/rbac-syncsecret/role_binding.yaml
- config/rbac/role_binding.yaml
- config/rbac/serviceaccount.yaml
- manifest_staging/deploy/rbac-secretproviderclass.yaml
- manifest_staging/deploy/rbac-secretprovidersyncing.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
Resolved #375. The CSI driver needs permissions across all namespaces
for secrets syncing and access to the host filesystem. A non-cluster
admin user should not have the ability to update or modify the CSI
driver due to these high level of privileges.
This change would require users upgrading from previous verisons of the
driver to run the following to cleanup old resources:
kubectl delete DaemonSet csi-secrets-store -namespace default
kubectl delete DaemonSet csi-secrets-store-windows -namespace default
kubectl delete ServiceAccount secrets-store-csi-driver -namespace default
Fixes #375
> deploy: set namespace as kube-system

- cmd/secrets-store-csi-driver/main.go
- pkg/csi-common/server.go
- pkg/errors/errors.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/provider_client.go
- pkg/secrets-store/provider_client_test.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/utils_test.go
- test/sanity/sanity_test.go
Create the provider GRPC clients during process initialization instead
of on-demand. The Dial() call is non-blocking and if the connection is
disrupted grpc should re-establish the connection. By configuring RPCs
to retry through a service configuration, this will ensure that when a
plugin is restarted the connection will be re-dialed and the RPC
retried.
Fixes #300
> feat: Reuse provider grpc clients

- Makefile
- cmd/secrets-store-csi-driver/main.go
- pkg/csi-common/driver.go
- pkg/rotation/reconciler.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/secrets-store_test.go
- pkg/version/version.go
- test/sanity/sanity_test.go
Adds pprof profiling
- Uses `6065` as default port to avoid conflicts with other processes running profiling
Fixes #
Example user agent:
```
➜ _output/secrets-store-csi --enable-pprof
I1130 12:18:21.153207   35656 main.go:85] Starting profiling on port 6065
I1130 12:18:21.153327   35656 main.go:92] user agent: csi-secrets-store/controller/v0.0.17 (darwin/amd64) d19088bd/2020-11-30-12:17
I1130 12:18:21.153339   35656 exporter.go:33] metrics backend: prometheus
```
> feat: add pprof profiling

- Makefile
- manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
- manifest_staging/charts/secrets-store-csi-driver/templates/csidriver.yaml
- Enables helm linting as part of CI
- Adds logic to determine the `CSIDriver` apiVersion
Fixes #319 
Fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/333
> feat: csidriver object api version v1

- Makefile
- docker/Makefile
- docker/build.sh
- Bumps driver version to `v0.0.18` for release
- Adds ldflags changes
Fixes #398
> chore: bump driver version to v0.0.18

- go.mod
- pkg/metrics/exporter.go
- pkg/metrics/prometheus_exporter.go
- Use controller-runtime prom registry to init exporter. This will publish `controller-runtime` and `driver` metrics to the same url `http://localhost:<metrics addr>/metrics`
Fixes #411 
> feat: use common port for all metrics

- Makefile
- docker/Makefile
> chore: bump driver version to v0.0.19

- Makefile
- test/bats/vault.bats
Fixes the tests that got broken with the release of Vault provider [0.0.7](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/releases/tag/0.0.7), and the update of `deploy/` on `master` to use that release - raising this was just dependent on getting the fix in https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/pull/58 merged first.
Fixes #429.
> Update e2e tests for gRPC Vault provider release

- Makefile
- docker/BASEIMAGE
- docker/Dockerfile
- docker/Makefile
> chore: update debian-base image to buster-v1.3.0

- docs/book/install-and-build.sh
See https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html for more details.
Thanks!
> Update mdbook to 0.4.5 to fix CVE-2020-26297

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
- Sets `secrets-store` container as default container for log
Fixes #
> feat: set secrets-store default container for log

- Makefile
- docker/BASEIMAGE
- docker/BASEIMAGE_CORE
- docker/Dockerfile
- docker/Makefile
- Bump debian base image to `us.gcr.io/k8s-artifacts-prod/build-image/debian-base-amd64:buster-v1.4.0`
Fixes #
> release: bump version to v0.0.20

- docker/cloudbuild.yaml
cloudbuild is taking longer than usual to finish building the images. Setting the timeout to `1h` instead so the build job can complete.
Ref build: https://console.cloud.google.com/cloud-build/builds;region=global/72ce7925-5706-4070-84ef-71521f772ff6?project=k8s-staging-csi-secrets-store
Fixes #
> chore: increase cloudbuild timeout to 1h

- docs/book/src/providers.md
Fixes broken urls in the providers doc
Fixes #
> docs: fix urls in providers doc

- docs/book/src/getting-started/usage.md
**why we need it**:
Links in `https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html` are broken.
This CR simply fix the link by referring to files in github repo.
N/A
> docs: update doc links in usage doc

- cmd/secrets-store-csi-driver/main.go
- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- pkg/cache/README.md
- pkg/cache/cache.go
- pkg/cache/doc.go
- pkg/cache/informer_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/k8s/store.go
- pkg/k8s/store_test.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
The `pkg/cache` added as part of this PR is copied from the cache pkg in controller-runtime.
Fixes #459 
Docs: https://docs.google.com/document/d/1ba8gTC-i33Df6uiOB8rW8jBX2B0lK8LszUjYlPzNwlQ/edit?usp=sharing
Based on load testing with a 100 node cluster:
- With v0.0.20, csi pod memory goes up to 110Mi for just 200 pods using csi, 7k pods total and 3k secrets
- With the patch, csi pod memory is ~50Mi with  4.5k pods with csi volume, 11k pods total and 3k secrets
> feat: add filtered watch for reconcile

- test/bats/vault.bats
- Update the vault deployment manifests to a specific commit instead of master. More info on the change here: https://github.com/hashicorp/vault-csi-provider/issues/74
partially fixes: #483 
> test: update vault e2e to use versioned deployment

- docs/book/src/concepts.md
- docs/book/src/getting-started/installation.md
- docs/book/src/introduction.md
- manifest_staging/deploy/csidriver-1.15.yaml
- `1.15` was deprecated on `2020-05-06` and the minimum requirement for using the CSI driver is `1.16`. So removing the `1.15` manifests. 
- Adding supported providers to introduction to make it easier for new users.
Fixes #
> chore: remove v1.15 yamls and update doc

- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- test/bats/azure.bats
- test/bats/vault.bats
Came across this issue while testing with older Kubernetes releases where the API server allows duplication of owner references. Although it doesn't have an impact on the core functionality of gc, it could lead to large objects if the owner refs are duplicated. This was fixed in this PR: https://github.com/kubernetes/kubernetes/pull/96185. 
Fixing the check to ensure we don't append the same owner reference twice and updating tests to conform with it. 
Fixes #
> fix: prevent duplicate owner references

- pkg/secrets-store/provider_client.go
- test/bats/azure.bats
Windows grpc connections are currently broken:
```
E0324 17:53:17.547284    6228 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline-crd, err: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp: address unix://C:\\k\\secrets-store-csi-providers/azure.sock: too many colons in address"
```
Believe this was caused by https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/462 where `grpc.Dial` was replaced with [`grpc.DialContext`](https://pkg.go.dev/google.golang.org/grpc#DialContext).
**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> dial: grpc naming is not compatible with windows unix socket

- Makefile
- docker/BASEIMAGE_CORE
- docker/windows.Dockerfile
Update `servercore` base image reference to `windows-servercore-cache` to speed up builds.
Fixes #
> chore: update servercore reference to windows-servercore-cache

- test/bats/azure.bats
- test/bats/gcp.bats
- test/bats/tests/azure/deployment-synck8s-azure.yaml
- test/bats/tests/azure/deployment-two-synck8s-azure.yaml
- test/bats/tests/azure/pod-azure-inline-volume-multiple-spc.yaml
- test/bats/tests/azure/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/azure/rotation/pod-synck8s-azure.yaml
- test/bats/tests/gcp/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/vault/deployment-synck8s.yaml
- test/bats/tests/vault/deployment-two-synck8s.yaml
- test/bats/tests/vault/pod-vault-inline-volume-multiple-spc.yaml
- test/bats/tests/vault/pod-vault-inline-volume-secretproviderclass.yaml
- test/bats/vault.bats
- Switches to using lightweight busybox image for tests. This image `k8s.gcr.io/e2e-test-images/busybox:1.29` is multi-os and can be used for windows as well. 
- Reduces windows tests run time by 50%
Fixes #
> test: update tests to use multi-os image

- docs/book/src/getting-started/usage.md
- docs/book/src/topics/set-as-env-var.md
- docs/book/src/topics/sync-as-kubernetes-secret.md
- sample/ingress-controller-tls/README.md
Now that #480 is merged with changes to file name, updating the urls in the docs and switching to use multi-os image for examples
Fixes #
> docs: use multi-os image for examples and update urls

- docker/BASEIMAGE
- docker/Dockerfile
- updates debian base image to `debian-base-amd64:buster-v1.5.0`
Fixes #
> chore: update debian base to buster-v1.5.0

- docs/book/src/SUMMARY.md
- docs/book/src/load-tests.md
- docs/design/README.md
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
- adds docs for load testing specs and results
- adds `--filtered-secret-watch` flag to the manifests
- updates design doc and adds load test optimization to the list
Fixes #111
> docs: add load test spec and results

- Makefile
- docker/Makefile
Bump version to `v0.0.21` to prepare for release.
Fixes #
> chore: bump version to v0.0.21

- manifest_staging/deploy/csidriver.yaml
Updates the `apiVersion` to `storage.k8s.io/v1` for csidriver in `manifest_staging/deploy/csidriver.yaml`
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/403
> fix: updates CSIDriver api ver to storage.k8s.io/v1

- pkg/secrets-store/nodeserver.go
the k8s.io/mount-utils package includes necessary logic:
https://github.com/kubernetes/mount-utils/blob/77a9b3dc97f9e87135fbdc74e84ab9611bcf9a1c/mount_windows.go#L215
I noticed this when going through some windows specific code paths and think its probably better to rely on the mounter to take care of this logic instead of including it in our unmount handler
N/A
> cleanup: remove windows file deletion on unmount

- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/provider_client_test.go
- pkg/util/fileutil/atomic_writer.go
- pkg/util/fileutil/atomic_writer_test.go
- pkg/util/fileutil/filesystem.go
- pkg/util/fileutil/filesystem_test.go
- pkg/util/fileutil/writer.go
- pkg/util/fileutil/writer_test.go
When files are returned in the grpc response, the driver will use the `atomic_writer.go` code to write the files into the mount. This is the same file writer used for `ConfigMap` and `Secret` objects currently.
#481 only really included the file path validation logic. This PR updates the vendored code unchanged (other than package name and comment).
Benefits include:
* re-use k8s code
* supports nested paths
* will remove files that are not in the update
Unfortunately files written the "regular" way are not updated by the atomic writer, so I've added unit tests and a helper `cleanupProviderFiles` to ensure that a path mounted using the old style will be correctly updated if the new style is deployed.
Additionally using the atomic writer means that …
> feat: use the atomic file writer

- Makefile
- docs/RELEASE.md
- Updates makefile target for automating release
- Updates release doc
Fixes #
> chore: update release docs and makefile targets

- Makefile
- docker/Makefile
Following release process at https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/RELEASE.md#versioning to build v0.0.22
Fixes #
> Bump versions for v0.0.22

- docker/cloudbuild.yaml
- pkg/secrets-store/nodeserver.go
- Fixes error when the file contents still exist
```bash
I0517 18:47:49.349641    3820 utils.go:76] GRPC request: {"target_path":"c:\\var\\lib\\kubelet\\pods\\5a9c8959-98de-4a7d-b3a9-36ee6b25c9cb\\volumes\\kubernetes.io~csi\\secrets-store-inline\\mount","volume_id":"csi-fd831ea73cd95fa276590bbccaece8e5c0c4f03dd768f6585cbb6ac80f30dd12"}
W0517 18:47:49.349698    3820 mount_helper_common.go:129] Warning: "c:\\var\\lib\\kubelet\\pods\\5a9c8959-98de-4a7d-b3a9-36ee6b25c9cb\\volumes\\kubernetes.io~csi\\secrets-store-inline\\mount" is not a mountpoint, deleting
E0517 18:47:49.353861    3820 nodeserver.go:230] "failed to clean and unmount target path" err="remove …
```
> fix: windows targetpath cleanup as part of node unpublish

- docs/RELEASE.md
help author release notes by adding a link to get all commits in a release
Fixes #
> release: add a link to branch compare

- Makefile
- hack/update-codegen.sh
- hack/verify-codegen.sh
- Enables `shellcheck` as part of CI
- Fixes errors after running `shellcheck`
Fixes #
> ci: enable shellcheck and fix errors

- docs/book/src/topics/set-as-env-var.md
**What this PR does / why we need it**: mainly fix `env` indent
> docs: set-as-env-var pod indent

- Makefile
- Adds psp conditional to `make manifests`
Fixes #549 
> chore: add psp snippet to manifests target

- Makefile
Report code coverage for unit test.
Fixes #
> Add test coverage report into Makefile for unit test

- Makefile
- docker/BASEIMAGE
- docker/Dockerfile
- docker/Makefile
- Bumps docker base image to debian-base-amd64:buster-v1.6.0
- Fixes CVE-2021-3520
Fixes #561 
> fix: CVE-2021-3520

- docker/BASEIMAGE
- docker/Dockerfile
Updates to debian-base v1.7.0 that resolves CVE-2021-3520. Removes cifs-utils as it's not
required for the driver.
Fixes #
> chore: update to debian-base v1.7.0

- Makefile
With os.WriteFile, it requires golang 1.16 to continue the build process.
Fixes #
N/A
> Add golang verison validate at Makefile

- Makefile
- docker/Dockerfile
- docker/windows.Dockerfile
Some corporate environments block access to `proxy.golang.org`. When building secrets-store-csi-driver in a container, setting `GOPROXY=direct` is not propagated, and even when it is, the absence of `git` causes builds to fail.
Fixes #570
You're awesome. Remember that.
> Added GOPROXY propagation to container builds

- docs/book/src/providers.md
Fix the default volume path for providers in the docs.
Fixes #573 
> docs: fix the default volume path for providers

- pkg/csi-common/controllerserver-default.go
- pkg/csi-common/identityserver-default.go
- pkg/csi-common/nodeserver-default.go
- pkg/csi-common/utils.go
- pkg/secrets-store/controllerserver.go
- pkg/secrets-store/identityserver.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/utils.go
replace "golang.org/x/net/context" import with "context"
Refer:
grpc-ecosystem/go-grpc-middleware#175
grpc/grpc-go#2439
Fixes #540 
N/A
> Replace golang.org/x/net/context with context

- pkg/secrets-store/provider_client.go
- pkg/secrets-store/provider_client_test.go
- Generates log to configure `--max-call-recv-msg-size` if the gRPC error is `ResourceExhausted` and not machine limit error
Fixes #536 
> chore: generate log if grpc message size larger than max

- Makefile
- docker/BASEIMAGE
- docker/Dockerfile
- docker/windows.Dockerfile
- Adds `arm64` build for Linux images
- Refactors dockerfile
Fixes #525 
> feat: add arm64 build

- README.md
- docs/MEMBERSHIP.md
- Adds "Getting involved and contributing" section to the readme.
- Adds the membership criteria doc
Fixes #
The `Getting involved and contributing` section has been taken from the cluster-api projects.
> docs: add membership criteria and getting involved section

- docs/book/src/getting-started/installation.md
- Add AWS provider reference in the provider install section
Fixes #
> docs: add aws provider ref in install provider

- Makefile
- docker/build.sh
- Enables qemu for multi-arch builds
- Fixes shellcheck errors in docker folder
Fixes #558 
> chore: enable qemu for multi-arch

- Makefile
- config/rbac-rotation/kustomization.yaml
- config/rbac-rotation/role.yaml
- config/rbac-rotation/role_binding.yaml
- docs/book/src/getting-started/installation.md
- manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation_binding.yaml
- manifest_staging/deploy/rbac-secretproviderrotation.yaml
- pkg/rotation/reconciler.go
- test/bats/aws.bats
- test/bats/azure.bats
- test/bats/gcp.bats
- test/bats/vault.bats
- Adds rbac clusterrole and binding for rotation reconciler to use with `nodePublishSecretRef`
Fixes #
> feat: add rbac role and binding for rotation

- Makefile
- docker/Makefile
> chore: bump version to v0.0.23

- docs/book/src/getting-started/upgrades.md
- Adds upgrade instruction for `v0.0.23` release
Fixes #
> docs: add upgrade instruction for v0.0.23

- test/bats/azure.bats
- test/bats/gcp.bats
- Adds test for `--filtered-watch-secret=false`
Fixes #
> test: add e2e for `--filtered-watch-secret=false`

- Makefile
- docker/BASEIMAGE
- docker/Dockerfile
- docker/Makefile
- Updates to debian-base `v1.7.2`
- Updates packages to fix CVE's
```bash
+-------------+------------------+----------+-------------------+-----------------+--------------------------------+------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |             TITLE              |                URL                 |
+-------------+------------------+----------+-------------------+-----------------+--------------------------------+------------------------------------+
| libgcrypt20 | CVE-2021-33560   | HIGH     | 1.8.4-5           | 1.8.4-5+deb10u1 | libgcrypt: mishandles ElGamal  | avd.aquasec.com/nvd/cve-2021-33560 |
| …
```
> chore: update to debian-base v1.7.2 and update packages to fix CVEs

- cmd/secrets-store-csi-driver/main.go
Use `DynamicRESTMapper` to dynamically discovers resource types at runtime. Using `WithLazyDiscovery` prevents the RESTMapper from discovering REST mappings until an API call is made.
- When CSI driver is deployed in a large cluster this can prevent concurrent GET requests from all the driver pods to discover resources as part of client initialization. 
Fixes #
> feat: use DynamicRESTMapper for manager

- controllers/secretproviderclasspodstatus_controller.go
- pkg/rotation/reconciler.go
- Adds a warning message to set `syncSecret.enabled=true` if the error is forbidden when CREATING/PATCHING/UPDATING kubernetes secret. 
Fixes #
> chore: add warning message for sync secret forbidden error

- apis/v1alpha1/secretproviderclass_types.go
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
- test/bats/vault.bats
To support k8s secrets annotations
Fixes #356 
> Possibility to annotate the created secret with CSI driver

- docs/book/src/concepts.md
- docs/book/src/getting-started/installation.md
- docs/book/src/introduction.md
More prominently display optional parameters when installing the CSI driver that will be commonly used.
Fixes #618
I also alphabetized the list of providers
> docs: link and mention optional features

- test/bats/azure.bats
- test/bats/tests/azure/deployment-synck8s-azure.yaml
- test/bats/tests/azure/deployment-two-synck8s-azure.yaml
- test/bats/tests/azure/pod-azure-inline-volume-multiple-spc.yaml
- test/bats/tests/azure/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/azure/rotation/pod-synck8s-azure.yaml
- Adds `kubernetes.io/os` node selector to schedule pods on linux/windows nodes for azure tests.
Fixes #619 
> test: add kubernetes.io/os nodeselector for azure tests

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Move the default container annotation out of the conditional.
Fixes #
> helm: move default annotations out of conditional

- test/bats/aws.bats
- test/bats/gcp.bats
Only relies on `kubectl wait` to check if the pod is ready as part of the e2e. Using `wait_for_process` in addition to `kubectl wait` will lead the tests to timeout. This change will make the tests fail fast. 
Fixes #
> e2e: use kubectl wait to check if pods ready

- test/bats/aws.bats
- test/bats/azure.bats
- test/bats/gcp.bats
- test/bats/helpers.bash
- test/bats/vault.bats
#526 removed some code and integration tests passed. It was only through manual verification that it was discovered that deletion before unmount was actually required: #545
Fixes #546
> e2e: ensure pod deletion is successful

- deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
Secrets store driver pods do not run properly on Windows nodes due to incompatibility with specific attributes.
**Which issue(s) this PR fixes** 
Fixes #624 
> Fix Windows nodes compatibility issues in pod definition

- deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/625 removed securityContext from deploy folder. Adding it back and making the change in `manifest_staging` folder so we can promote during release. 
Fixes #
> chore: revert changes from deploy and add to manifest_staging

- test/bats/helpers.bash
- test/bats/tests/azure/job_templates/kubernetes_windows.json
- Gets log for sidecar containers
Fixes #
> e2e: get logs for sidecar containers

- test/bats/azure.bats
- test/bats/gcp.bats
- test/bats/helpers.bash
- test/bats/tests/gcp/gcp_v1alpha1_secretproviderclass.yaml
- test/bats/tests/gcp/pod-secrets-store-inline-volume-crd.yaml
Update GCP tests to use workload identity in the secret mount (provided through prow).
Fixes #640 and #507
> test: gcp use workload id instead of node publish

- Makefile
- docker/cloudbuild.yaml
- docker/crd.Dockerfile
- manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
Switches to using scratch base image for the driver-crds. The entrypoint is set to kubectl to prevent shell access. Enabled image scan for the `driver-crds` image.
Fixes #
> chore: switch to using distroless base image for driver-crds

- docs/book/src/getting-started/upgrades.md
Adds note about handling CRDs install and upgrade via helm. 
Ref https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/623#pullrequestreview-710930824
Fixes #
> docs: adds note about crd upgrade

- docker/Dockerfile
```bash
➜ trivy --exit-code 1 --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL e2e/driver:v0.1.0-alpha.1-linux-amd64
2021-07-21T21:42:25.978Z	INFO	Need to update DB
2021-07-21T21:42:25.978Z	INFO	Downloading DB...
22.55 MiB / 22.55 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 12.86 MiB p/s 2s
2021-07-21T21:42:34.580Z	INFO	Detecting Debian vulnerabilities...
2021-07-21T21:42:34.588Z	INFO	Trivy skips scanning programming language libraries because no supported file was detected …
```
> dockerfile: fix CVE-2021-33910

- docker/build.sh
- test/bats/azure.bats
The staging charts dir are promoted to charts only after image is built. So we should use the manifest_staging charts for building the crds image.
Fixes #
> chore: switch to using manifest_staging charts in the build

- Makefile
- docker/Makefile
> chore: bump version to v0.1.0 in release-0.1

- docker/build.sh
Cherry pick of #652 on release-0.1.
#652: fix: add ARCH build arg for driver-crds
> Automated cherry pick of #652: fix: add ARCH build arg for driver-crds

- hack/cherry_pick_pull.sh
Adds a script for cherry pick to make it easier for cherry picks to release branches.
This script is taken as is from https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh
All credits to contributors.
Fixes #
> chore: add cherry_pick_pull script from kubernetes

- manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
- test/bats/azure.bats
The crds have been moved from the templates/ to crds/ folder. When helm upgrade is run, helm will delete the crds because they're no longer in the generated template. To prevent deletion, we patch the 2 CRDs with the "helm.sh/resource-policy": "keep". Helm will skip deletion of resources with these annotation. Also, converted the hooks to a job as helm kills the pod before kubectl exec is run. With job, helm waits until the pod is run and reaches completion.
Fixes #
> feat: add keep-crd upgrade hook

- Makefile
- This fixes the upgrade test failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-secrets-store-csi-driver-upgrade-test-azure/1418269724701102080
- Should also help us catch the issue with https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/656
Fixes #
> e2e: add driver-crd image to e2e-helm-upgrade target

- test/bats/azure.bats
- test/bats/gcp.bats
- Using `kubectl exec` output instead of `kubectl cp`. `kubectl cp` for symlinks fails with the error:
```bash
warning: skipping symlink: "here" -> "..data/secretalias" (consider using "kubectl exec -n "" "secrets-store-inline-rotation" -- tar cf - "/mnt/secrets-store/secretalias/" | tar xf -")
```
Ref: https://github.com/kubernetes/kubernetes/issues/78211
Fixes #663 
> test: use kubectl exec instead of cp

- test/bats/azure.bats
- test/bats/gcp.bats
Cherry pick of #664 on release-0.1.
#664: test: use kubectl exec instead of cp
> Automated cherry pick of #664: test: use kubectl exec instead of cp

- manifest_staging/charts/secrets-store-csi-driver/templates/_helpers.tpl
Helm charts that package this as a dependency can override the fullname using the value. By default, helm appends the release chart name as prefix for the subchart which can make the name really long. Helm charts that package this as a dependency can use `fullnameOverride: secrets-store-csi-driver` to ensure the parent chart release name isn't appended to the driver fullname. 
Fixes #665 
> helm: add option to configure fullnameOverride

- docs/book/src/load-tests.md
Updating the document to mention `--filtered-watch-secret` is now enabled by default in `v0.1.0`
Fixes #
> docs: update load test doc for filtered watch secret

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
PodMonitors in the prometheus operator only supports defining port names and not numbers.
To be able to call on the name we need to define the port name in the pod.
Fixes #
> chore: Add metrics port definition to DS

- pkg/util/fileutil/atomic_writer.go
- pkg/util/fileutil/atomic_writer_test.go
Signed-off-by: Katsuya Yamaguchi <pupupu0701@gmail.com>
The `io/ioutil` package is deprecated (https://golang.org/doc/go1.16#ioutil).
Fixes #578
> chore: Migrate from deprecated io/ioutil package to using os package

- Makefile
- test/bats/azure.bats
This PR adds e2e test on deploy manifest for Secrets Store CSI driver. Ref #297 
Fixes #
> test: adds make target for deploy manifest

- docker/BASEIMAGE
- docker/Dockerfile
- Bumps debian base image to `buster-v1.9.0`
Fixes #
> chore: update debian base to buster-v1.9.0

- manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
Signed-off-by: Frédéric Marchand <fred@mautadine.com>
Use the defined toleration and nodeSelector for the crds jobs.
Fixes #
> helm: use same toleration and nodeselector for crd-hook jobs

- Makefile
- docker/Makefile
> chore: bump version to v0.2.0 in release-0.2

- docs/RELEASE.md
> chore: update release docs with release branches

- .github/workflows/chart.yaml
- Makefile
- Adds github action to package and publish helm charts on GitHub pages.
- I've created the `gh-pages` branch with the updated index for url `https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts` for all the current releases: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/gh-pages
- Updates the `promote-staging-manifest` makefile target to remove `helm package`. The helm charts are packaged and published by the GitHub action.
Fixes #687 
> ci: add workflow for publishing helm charts

- pkg/util/secretutil/secret.go
- pkg/util/secretutil/secret_test.go
In the secret sync, we're only supporting the core secret types with default type always being `Opaque`. As per the [Kubernetes secret types](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) documentation, there are no constraints imposed by Kubernetes on the type of the secret. Anything the user providers as type is used and persisted. Following the same pattern in our driver to remove the constraint and set type as `Opaque` only when no secret type is set.
Fixes …
> fix: remove constraints on secret type name

- cmd/secrets-store-csi-driver/main.go
- pkg/k8s/store.go
- pkg/k8s/store_test.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
Filtered watch secret has been enabled by default in `v0.1.0` release. This PR makes the flag configuration no-op to not allow disabling the feature. The flag will be removed altogether from code, deployment and helm charts in n+2 releases.
ref https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/597
> chore: make `--filtered-watch-secret` flag no-op

- test/bats/azure.bats
Based on https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/695/pull-secrets-store-csi-driver-e2e-windows/1428401281927483392, the `node-driver-registrar` was restarted 5 times before the driver registration was complete. Increasing the pod timeout to `300s` for the pod in an attempt to deflake the test during startup.
Logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/695/pull-secrets-store-csi-driver-e2e-windows/1428401281927483392/artifacts/2021-08-19T172835/pods-describe.txt
**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> test: set first pod ready wait timeout to 300s

- docker/cloudbuild.yaml
Currently we build linux/amd64, linux/arm64, windows/1809, windows/1903, windows/1909 and windows/2004 images with cloudbuild. This takes ~1h10m to complete. Use larger machine type N1_HIGHCPU_8 for cloudbuild jobs to speed up the build. Also, update the cloudbuild base image to a newer version.
Note: This machine type is used across all kubernetes builds.
Fixes #
> chore: use N1_HIGHCPU_8 for cloudbuild and update cloudbuild image

- Makefile
- docker/Makefile
> chore: bump version to v0.3.0 in release-0.3

- docs/RELEASE.md
Update based on notes from yesterday's 0.3.0 release
Fixes #
> chore: update RELEASE docs based on v0.3.0 experience

- Makefile
- docker/Makefile
In #716 we missed bumping the version numbers on the `master` branch (which are included in `release-0.3` branch)
Fixes #
> chore: missed updates from #716

- docs/book/src/getting-started/installation.md
- docs/book/src/getting-started/upgrades.md
- manifest_staging/charts/secrets-store-csi-driver/README.md
Fixes  `kuberentes` => `kubernetes`
Ref : https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/695#issuecomment-909874668
Fixes #
> docs: fix typo in docs

- charts/secrets-store-csi-driver/README.md
Additional changes on top of https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/720. The readme in charts is used by users for configuring the charts so fixing the typo in that doc too. 
Fixes #
> docs: fix typo in chart url

- .github/PULL_REQUEST_TEMPLATE.md
- docker/cloudbuild.yaml
- docs/RELEASE.md
- docs/Release_Management.md
- docs/book/src/getting-started/installation.md
- docs/book/src/getting-started/usage.md
- docs/book/src/providers.md
- Updates doc references from `master` to `main` as part of the rename.
Ref https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/617
> chore: rename references from master to main

- pkg/metrics/exporter.go
- Removes the deprecated `prometheus-port` flag. Use `--metrics-addr` instead.
Fixes #
> chore: remove deprecated --prometheus-port flag

- docs/book/src/topics/metrics.md
- docs/book/src/troubleshooting.md
- Adds `port-forward` commands and flag for enabling pprof/metrics.
Fixes #
> docs: add detail about pprof and metrics endpoint

- .github/workflows/e2e.yaml
- Makefile
- charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
- docs/RELEASE.md
This PRs adds github action to run e2e tests on demand. This will help run e2e tests on staging images before releasing them.
Fixes #688 
> ci: add workflow for e2e using staging images

- cmd/secrets-store-csi-driver/main.go
- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- pkg/k8s/store.go
- pkg/k8s/store_test.go
- pkg/metrics/exporter.go
- pkg/metrics/prometheus_exporter.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/controllerserver.go
- pkg/secrets-store/identityserver.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/provider_client.go
- pkg/secrets-store/provider_client_test.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/server.go
- pkg/util/fileutil/atomic_writer.go
- pkg/util/fileutil/filesystem_test.go
- pkg/util/secretutil/secret_test.go
- provider/fake/fake_server.go
- test/e2eprovider/e2e_provider.go
- test/e2eprovider/server/server_test.go
- test/sanity/sanity_test.go
- Updates all the logs to use structured logging with klog
- Replaced `Fatalf` with `ErrorS` followed by `os.Exit(1)` as recommended in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions-to-structured-equivalent
- Fix imports structure across all the packages. The format used in this project is
```bash
import (
std packages
internal packages
external packages
)
```
Fixes #
> chore: use structured logging and update imports order

- cmd/secrets-store-csi-driver/main.go
- controllers/secretproviderclasspodstatus_controller_test.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/secrets-store.go
- pkg/secrets-store/utils.go
- pkg/secrets-store/utils_test.go
- pkg/util/spcpsutil/spcps.go
- pkg/util/spcpsutil/spcps_test.go
- test/sanity/sanity_test.go
-  Create or Update `SecretProviderClassPodStatus`. For pods scheduled by statefulsets the pod name is deterministic. In a scenario where this pod with name `pod-0` gets rescheduled to a new and there is a delay in garbage collection we would skip the `SecretProviderClassPodStatus` creation as it already exists. However when the garbage collection happens, the SPCPS will be deleted as it's still referencing the old owner (UID) with the same pod name which no longer exists. Using update in addition will update the node label and owner correctly post mount. 
- Replaces deprecated `fake.NewFakeClientWithScheme` with `fake.NewClientBuilder`
- Sorts the object version before setting in …
> feat: create or update secretproviderclasspodstatus post mount

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
Sets the `initialDelaySeconds` and `timeoutSeconds` for the node-driver-registrar livenessprobe check. 
- The default `timeoutSeconds` of 1s is honored starting from Kubernetes 1.20 and is aggressive. Setting the value to 15s which is appropriate for linux and windows.
- Setting `initialDelaySeconds` to 30s to provide time for the socket to be created and driver to be registered during startup of the driver pods.
- Set resource requests to 100m/100Mi for all the containers. The limits are already 200m/200Mi for the `node-driver-registrar`, `livenessprobe` containers and 400m/400Mi for the secrets-store container.
Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness …
> chore: update the initialDelaySeconds and timeoutSeconds for node-driver-registrar livenessprobe

- .local/debug-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/deploy/secrets-store-csi-driver-windows.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
Deprecated annotation: `kubectl.kubernetes.io/default-logs-container`. Using `kubectl.kubernetes.io/default-container` instead. Ref: https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container
Fixes #
> chore: use `kubectl.kubernetes.io/default-container` annotation

- Makefile
- docker/Makefile
> chore: bump version to v1.0.0-rc.0 in release-1.0

- test/bats/tests/vault/pod-vault-rotation.yaml
- test/bats/vault.bats
**What this PR does / why we need it**: For feature support matrix, ensure vault works with rotation.
Fixes #
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/724
> tests: add e2e test for vault rotation

- .golangci.yml
Fixes #
Details: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/636
It passed: make lint-full, there are a few items is not list in this PR, for example goconst and gocyclo, which needs code change as well, once this PR is merged, I can pick up them up and fix the code changes.
> chore: enable additional linters

- docs/Release_Management.md
- docs/book/src/getting-started/installation.md
- Adds supported kubernetes versions for the driver
Fixes #
This change was inspired by the supported kubernetes version note in [gatekeeper](https://github.com/open-policy-agent/gatekeeper)
> docs: add supported kubernetes versions

- test/bats/e2e-provider.bats
- test/bats/helpers.bash
- Logs the secrets-store API version being tested as part of e2e
Sample output:
```bats
➜ bats -t test/bats/test.bats                            
1..2
Testing secrets-store API version secrets-store.csi.x-k8s.io/v1
ok 1 secretproviderclasses crd is established
ok 2 secretproviderclasspodstatuses crd is established
```
Fixes #
> test: log the secrets-store API version

- Makefile
- docker/Makefile
Steps 4 and 5 from https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/RELEASE.md#versioning for `v1.0.0-rc.1` release
> chore: bump version 1.0.0 rc.1

- docker/BASEIMAGE
Cherry pick of #769 on release-1.0.
#769: fix: update base image core for ltsc2022
> Automated cherry pick of #769: fix: update base image core for ltsc2022

- .github/workflows/e2e.yaml
- Enables k8s version matrix for the e2e workflow
Test run: https://github.com/aramase/secrets-store-csi-driver/actions/runs/1309023862
Fixes #
> test: add k8s test matrix for staging e2e

- Makefile
- docker/build.sh
- docker/crd.Dockerfile
- Updates dockerfile to use `TARGETARCH` instead of `ARCH` arg
- Updates docker build to use `buildx` for validating builds. Using `--progress=plain` to have the same output as `docker build`.
- Makes docker buildx builder name customizable and consolidates builder creation with running qemu
Fixes #
> chore: use TARGETARCH for image build and makefile update

- .github/workflows/markdown-link-check.yaml
- README.md
- docs/MEMBERSHIP.md
- docs/book/src/concepts.md
- docs/book/src/getting-started/usage.md
- sample/ingress-controller-tls/README.md
- Adds workflow for checking dead links in docs
- This will run as part of pull requests (non-blocking), periodically at 9AM everyday and on push to the main branch.
- Remove `sample` dir as it contains provider specific links and require maintenance. 
Fixes #806 
> ci: add markdown-link-check workflow

- manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
- Places `PodSecurityPolicy` for keep-crds upgrade job in `rbac.pspEnabled` conditional
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/816
> helm: check rbac.pspEnabled for keep-crds upgrade hook

- docker/BASEIMAGE
- docker/Dockerfile
> chore: update debian-base to bullseye-v1.1.0

- docker/Dockerfile
```bash
➜ trivy --exit-code 1 --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL k8s.gcr.io/build-image/debian-base:bullseye-v1.1.0
2022-01-04T13:40:52.026-0800	WARN	The root command will be removed. Please migrate to 'trivy image' command. See https://github.com/aquasecurity/trivy/discussions/1515
2022-01-04T13:40:52.073-0800	INFO	Need to update DB
2022-01-04T13:40:52.073-0800	INFO	Downloading DB...
25.32 MiB / 25.32 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 24.18 MiB p/s 1s …
```
> security: fix CVE-2021-43618

- pkg/util/secretutil/secret.go
Log the invalid key type in case of an error
Fixes #
> chore: log invalid key in error

- docker/cloudbuild.yaml
Cherry pick of #814 on release-1.0.
#814: images: use k8s-staging-test-infra/gcb-docker-gcloud
> Automated cherry pick of #814: images: use k8s-staging-test-infra/gcb-docker-gcloud

- docker/BASEIMAGE
- docker/Dockerfile
Cherry pick of #825 on release-1.0.
#825: chore: update debian-base to bullseye-v1.1.0
> Automated cherry pick of #825: chore: update debian-base to bullseye-v1.1.0

- docker/Dockerfile
Cherry pick of #826 on release-1.0.
#826: security: fix CVE-2021-43618
> Automated cherry pick of #826: security: fix CVE-2021-43618

- Makefile
- docker/Makefile
Steps 4 and 5 from https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/RELEASE.md#versioning for v1.0.1 release
> chore: bump version to 1.0.1 in release-1.0

- Makefile
- docker/Dockerfile
- docker/Makefile
```bash
gcr.io/k8s-staging-csi-secrets-store/driver:v1.0.0-e2e-73bc8002 (debian 11.1)
Total: 2 (MEDIUM: 2, HIGH: 0, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils | CVE-2021-3995    | MEDIUM   | 2.36.1-8          | 2.36.1-8+deb11u1 | util-linux: Unauthorized unmount     |
| …
```
> security: fix CVE-2021-3995, CVE-2021-3996

- Makefile
- docker/Dockerfile
- docker/Makefile
Cherry pick of #843 on release-1.0.
#843: security: fix CVE-2021-3995, CVE-2021-3996
> Automated cherry pick of #843: security: fix CVE-2021-3995, CVE-2021-3996

- pkg/k8s/token.go
- pkg/k8s/token_test.go
- [NewFilteredSharedInformerFactory](https://pkg.go.dev/k8s.io/client-go@v0.23.0/informers?utm_source=gopls#NewFilteredSharedInformerFactory) is deprecated and recommendation is to use `NewSharedInformerFactoryWithOptions` instead.
- Adds missing license in `token_test.go`
Fixes #
> refactor: use NewSharedInformerFactoryWithOptions for new shared informer

- apis/v1alpha1/secretproviderclass_types.go
- apis/v1alpha1/secretproviderclasspodstatus_types.go
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- Marks `v1alpha1` as deprecated with a warning message for `SecretProviderClass`
```shell
➜ k apply -f ~/yamls/v1alpha1-csi-linux.yaml                                             
Warning: secrets-store.csi.x-k8s.io/v1alpha1 is deprecated. Use secrets-store.csi.x-k8s.io/v1 instead.
```
Fixes #
> chore: mark `v1alpha1` api version as deprecated

- .github/workflows/create-release.yaml
- .goreleaser.yml
- Use goreleaser for generating changelog when a new tag is published
Fixes #
Testing in my fork:
- https://github.com/aramase/secrets-store-csi-driver/releases/tag/v1.1.0
- https://github.com/aramase/secrets-store-csi-driver/releases/tag/v1.0.2
> ci: add goreleaser workflow for release

- Makefile
- docker/Makefile
> chore: bump version to v1.1.0-rc.0 in release-1.1

- .github/workflows/e2e.yaml
> ci: update e2e_mock_provider_tests kubernetes versions

- cmd/secrets-store-csi-driver/main.go
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/provider_client.go
- pkg/secrets-store/provider_client_test.go
- test/e2eprovider/e2e-provider-installer.yaml
This allows the driver to check multiple paths when looking for a provider,
addressing #823 as the semantically correct path is /var not /etc.
`-additional-provider-volume-paths` is added to so that providers that have not
migrated to the /var location will continue to operate.
In a future release when all supported providers are migrated to the /var path
the `-additional-provider-volume-paths` flag can be removed or changed to an
empty string.
Fixes #823
TODO:
> feat: support provider paths under /var/run

- test/bats/e2e-provider.bats
Check for tokenrequest role and rolebinding only when `tokenRequests` is configured in `CSIDriver`. Fixes inplace upgrade tests: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-secrets-store-csi-driver-inplace-upgrade-test-e2e-provider/1493900718866698240 
Fixes #
> test: conditionally check token requests role and binding

- cmd/secrets-store-csi-driver/main.go
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
- manifest_staging/charts/secrets-store-csi-driver/values.yaml
- manifest_staging/deploy/secrets-store-csi-driver.yaml
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/provider_client.go
- pkg/secrets-store/provider_client_test.go
- test/e2eprovider/e2e-provider-installer.yaml
Cherry pick of #851 on release-1.1.
#851: feat: support provider paths under /var/run
> Automated cherry pick of #851: feat: support provider paths under /var/run

- Makefile
- docker/Makefile
> chore: bump version to v1.1.0 in release-1.1

- cmd/secrets-store-csi-driver/main.go
- Fixes a panic issue when `--log-format-json=true`
Validated the fix:
```bash
➜ go run cmd/secrets-store-csi-driver/main.go
{"ts":1645724627732.689,"caller":"metrics/exporter.go:35","msg":"initializing metrics backend","v":0,"backend":"prometheus"}
{"ts":1645724627734.4478,"caller":"secrets-store-csi-driver/main.go:181","msg":"starting manager\n","v":0}
{"ts":1645724627835.707,"caller":"secrets-store/secrets-store.go:46","msg":"Initializing Secrets Store CSI Driver","v":0,"driver":"secrets-store.csi.k8s.io","version":"local-dev","buildTime":""}
{"ts":1645724627842.8486,"caller":"secrets-store/server.go:120","msg":"Listening for connections","v":0,"address":"/tmp/csi.sock"} …
```
> fix: panic when using `--log-format-json` is set to true

- cmd/secrets-store-csi-driver/main.go
Cherry pick of #888 on release-1.1.
#888: fix: panic when using --log-format-json
> Automated cherry pick of #888: fix: panic when using --log-format-json

- Makefile
- docker/Makefile
Steps 4 and 5 from https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/RELEASE.md#versioning for v1.1.1 release
> chore: bump version to 1.1.1 in release-1.1

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
Checks if additionalProviderPaths matches providerPaths to avoid duplicate volume mounts,
Fixes #897
> validate additionalProviderPaths does not contain providerPath

- Makefile
- docker/Dockerfile
- docker/Makefile
```bash
gcr.io/k8s-staging-csi-secrets-store/driver:v1.1.0-e2e-6a68de14 (debian 11.1)
Total: 2 (MEDIUM: 1, HIGH: 1, CRITICAL: 0)
+-----------+------------------+----------+-------------------+------------------+--------------------------------------+
|  LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+-----------+------------------+----------+-------------------+------------------+--------------------------------------+
| libssl1.1 | CVE-2022-0778    | HIGH     | 1.1.1k-1+deb11u1  | 1.1.1k-1+deb11u2 | The BN_mod_sqrt() function,          |
| …
```
> security: fix CVE-2022-0778, CVE-2021-4160

- Makefile
- docker/Dockerfile
- docker/Makefile
Cherry pick of #900 on release-1.1.
#900: security: fix CVE-2022-0778, CVE-2021-4160
> Automated cherry pick of #900: security: fix CVE-2022-0778, CVE-2021-4160

- docs/book/src/SUMMARY.md
- docs/book/src/topics/command-reference.md
**What this PR does / why we need it**: This is raised to add a new subpage under topics around command reference
Fixes #855 
**Special notes for your reviewer**: 
- Do let me know if **Command Reference** title works else we can update with **Command Line Arguments** or **Configuration Options**
> docs: add command reference

- docker/Dockerfile
- upgrading libc-bin due to CVE-2021-33574, CVE-2022-23218, CVE-2022-23219 and CVE-2021-43396
- upgrading libc6 due to CVE-2021-33574, CVE-2022-23218, CVE-2022-23219 and CVE-2021-43396
- upgrading libsystemd0 due to CVE-2021-3997
- upgrading libudev1 due to CVE-2021-3997
```bash
gcr.io/k8s-staging-csi-secrets-store/driver:v1.1.0-e2e-ddfae407 (debian 11.1)
Total: 10 (MEDIUM: 2, HIGH: 2, CRITICAL: 6)
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  | …
```
> security: fix CVEs

- docker/Dockerfile
Cherry pick of #914 on release-1.1.
#914: security: fix CVEs
> Automated cherry pick of #914: security: fix CVEs

- Makefile
- docker/Dockerfile
- docker/Makefile
Cherry pick of #923 on release-1.1.
#923: security: fix CVE-2018-25032 and update to
> Automated cherry pick of #923: security: fix CVE-2018-25032 and update to

- Makefile
- test/bats/akeyless.bats
- test/bats/tests/akeyless/pod-inline-volume-secretproviderclass.yaml
- test/bats/tests/akeyless/secretproviderclass.yaml
Adds tests using new CSI provider
Fixes #
> test: add e2e for akeyless csi provider

- docs/RELEASE.md
> docs: update instructions on generating release notes

- .github/workflows/e2e.yaml
- Remove Kubernetes version 1.20 from CI since it has reached EOL
- Update Kubernetes versions to latest in CI for supported releases
Fixes #
> ci: update kubernetes version matrix in staging e2e workflow

- test/bats/azure.bats
`helm upgrade` sub-command can upgrade an existing chart and install a new one, if the chart hasn’t been installed before. This will be used by the upgrade e2e tests.
Fixes #
> test: use helm upgrade --install for azure e2e

- docker/Dockerfile
> security: fix CVE-2022-1271

- docker/Dockerfile
Cherry pick of #934 on release-1.1.
#934: security: fix CVE-2022-1271
> Automated cherry pick of #934: security: fix CVE-2022-1271

- .github/workflows/markdown-link-check.yaml
- .markdownlinkcheck.json
- docs/book/src/SUMMARY.md
Links to https://docs.github.com/ raises a 403, which fails our markdown link checker.
See https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/136
> ci: fix markdown link check workflow failures

- test/bats/aws.bats
- test/bats/azure.bats
- test/bats/gcp.bats
- test/bats/vault.bats
- Trim down the supported provider test suite. The `e2e-provider` test will contain all the required tests.
Fixes #
> test: cleanup provider tests (part 1)

- docker/Dockerfile
```bash
e2e/driver:test-linux-amd64 (debian 11.3)
Total: 1 (MEDIUM: 0, HIGH: 0, CRITICAL: 1)
┌───────────┬───────────────┬──────────┬───────────────────┬──────────────────┬───────────────────────────────────────────────────┐
│  Library  │ Vulnerability │ Severity │ Installed Version │  Fixed Version   │                       Title                       │
├───────────┼───────────────┼──────────┼───────────────────┼──────────────────┼───────────────────────────────────────────────────┤
│ libssl1.1 │ CVE-2022-1292 │ CRITICAL │ 1.1.1n-0+deb11u1  │ 1.1.1n-0+deb11u2 │ openssl: c_rehash script allows command injection │
│           │               │          │                   │                  │ …
```
> security: fix CVE-2022-1292

- .github/workflows/e2e.yaml
/kind feature
- Adds kubernetes `v1.24` to staging image e2e matrix
Fixes #
**TODOs**:
> ci: add kubernetes 1.24 in e2e matrix

- docker/Dockerfile
/kind feature
- Update debian-base to bullseye-v1.3.0
Fixes #
**TODOs**:
> chore: update debian-base to bullseye-v1.3.0

- docker/Dockerfile
/kind bug
```bash
gcr.io/k8s-staging-csi-secrets-store/driver:v1.1.0-e2e-b2fdf40b (debian 11.3)
Total: 1 (MEDIUM: 1, HIGH: 0, CRITICAL: 0)
+---------+------------------+----------+-------------------+---------------+--------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                TITLE                 |
+---------+------------------+----------+-------------------+---------------+--------------------------------------+
| dpkg    | CVE-2022-1664    | MEDIUM   | 1.20.9            | 1.20.10       | [directory traversal for …
```
> security: fix CVE-2022-1664

- manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
bugfix for multiple entries in `linux.crds.podLabels`
/kind bug
if there are more than one `linux.crds.podLabels`, the helm chart won't work.
Fixes #
bugfix for this recently merged: #962 
**TODOs**:
> fix: multiple podLabels for linux.crds in helm charts

- manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
/kind bug
Helm chart upgrade fails because of the incorrect hook-weight.
Job resource from [/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/a5b207f5904874b20e00aa29416dda4e4162e2b2/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml#L81) and [/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/a5b207f5904874b20e00aa29416dda4e4162e2b2/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml#L81) should have higher hook-weight (lower priority) than other resources like ClusterRole, ClusterRoleBinding, ServiceAccount, …
> fix: increase hook-weight for crd upgrade jobs in helm charts

- .github/workflows/e2e.yaml
/kind bug
- Fixes failures with https://github.com/kubernetes-sigs/secrets-store-csi-driver/runs/7009334702?check_suite_focus=true
Fixes #
**TODOs**:
> ci: bump kind version to v0.14.0

- Makefile
- docker/Dockerfile
- docker/Makefile
/kind bug
```bash
e2e/driver:test-linux-amd64 (debian 11.3)
Total: 1 (MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌───────────┬───────────────┬──────────┬───────────────────┬──────────────────┬───────────────────────────────────────────────────────┐
│  Library  │ Vulnerability │ Severity │ Installed Version │  Fixed Version   │                         Title                         │
├───────────┼───────────────┼──────────┼───────────────────┼──────────────────┼───────────────────────────────────────────────────────┤
│ libssl1.1 │ CVE-2022-2068 │ MEDIUM   │ 1.1.1n-0+deb11u2  │ 1.1.1n-0+deb11u3 │ openssl: the c_rehash script allows command injection │
│           │ …
```
> security: fix CVE-2022-2068

- docker/Dockerfile
/kind feature
- Update debian-base to bullseye-v1.4.0
Fixes #
**TODOs**:
> chore: update debian-base to bullseye-v1.4.0

- Makefile
- docker/Makefile
/kind feature
- Bump image version to `v1.2.1` for release
Fixes #
**TODOs**:
> chore: bump version to v1.2.1 in release-1.2

- pkg/secrets-store/provider_client.go
- pkg/secrets-store/server.go
- pkg/secrets-store/utils.go
- pkg/util/fileutil/atomic_writer.go
- pkg/util/fileutil/writer_test.go
- pkg/util/runtimeutil/runtime.go
/kind bug
This PR introduces a fallback os.Lstat check in provider client for the provider socket. There is a known issue in windows using os.Stat() which happens randomly in 1809, 1903 but always fails in ltsc2022.
Fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/931
**TODOs**:
> fix: use `os.Lstat` to resolve `os.Stat` issue in windows

- Makefile
- docker/Makefile
/kind feature
Fixes #
**TODOs**:
> chore: bump version to v1.2.2 in release-1.2

- go.mod
- go.sum
- test/e2eprovider/go.mod
- test/e2eprovider/go.sum
/kind bug
Fixes CVE-2022-29526 - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-secrets-store-csi-driver-image-scan/1549227446891450368
Fixes #
**TODOs**:
> security: fix CVE-2022-29526

- Makefile
- docker/Dockerfile
- docker/Makefile
/kind feature
- update debian-base to bullseye-v1.4.1
Fixes #
**TODOs**:
> chore: update debian-base to bullseye-v1.4.1

- docs/book/src/release-management.md
> docs: add security vuln scanning to release mgmt

- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/server.go
- pkg/secrets-store/server_test.go
/kind bug
`protosanitizer` strips out sensitive information from the secrets field in the RPC request, however it doesn't handle
service account tokens in the volume context. Added a new wrapper function to sanitize sensitive information before sending it to the protosanitizer.
Fixes #
**TODOs**:
> fix: sanitize service account tokens in logs

- docker/BASEIMAGE
- docker/Dockerfile
/kind feature
- update debian-base to bullseye-v1.4.2
Fixes #
**TODOs**:
> chore: update debian-base to bullseye-v1.4.2

- .github/workflows/e2e.yaml
/kind feature
- Removes `v1.21` as it's EOL and adds `v1.25` to the staging image test matrix.
Fixes #
**TODOs**:
> ci: bump kubernetes version to v1.25.0

- docker/Dockerfile
/kind bug
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-secrets-store-csi-driver-image-scan/1569164682281881600
Fixes #
**TODOs**:
> security: fix multiple CVEs

- docker/Dockerfile
/kind cleanup
- Run `apt update && apt upgrade -y` to patch CVEs instead of managing individual packages.
Fixes #
**TODOs**:
> chore: run apt update && apt upgrade -y in dockerfile

- go.mod
- go.sum
- test/e2eprovider/go.mod
- test/e2eprovider/go.sum
/kind bug
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-secrets-store-csi-driver-image-scan/1570614670161612800
Fixes #
**TODOs**:
> security: fix CVE-2022-27664

- go.mod
- go.sum
- pkg/util/secretutil/secret.go
- pkg/util/secretutil/secret_test.go
/kind bug
Fixes #1057
**TODOs**:
> fix: handles pfx certs in k8s secrets sync

- docker/Dockerfile
/kind bug
- Use `golang:1.19` builder for driver
Fixes #
**TODOs**:
> chore: use `golang:1.19` builder for driver

- .github/workflows/codeql.yaml
- pkg/util/fileutil/filesystem.go
- pkg/util/fileutil/filesystem_test.go
/kind bug
ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/security/code-scanning/1
Fixes #
**TODOs**:
> fix: escape dot in target path regex

- manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
/kind bug
Annotations in `secrets-store-csi-driver` daemonset was put in wrong position in #1043, this patch fixes it. 
Fixes #1093
**TODOs**:
> fix: put annotations in right position of daemonset

- Makefile
- docker/crd.Dockerfile
/kind feature
- Update to kubectl `1.25.4` in driver-crds
Fixes #
**TODOs**:
> chore: use kubectl 1.25.4 in driver-crds

- Makefile
- docker/crd.Dockerfile
/kind feature
- use kubectl v1.26.0 in driver-crds
- reenable trivy scan for binaries in `driver-crds`
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1075
**TODOs**:
> chore: use kubectl v1.26.0 in driver-crds

- Makefile
- docker/Makefile
/kind feature
- bump version to v1.3.0 in release-1.3
Fixes #
**TODOs**:
> chore: bump version to v1.3.0 in release-1.3

- .github/workflows/e2e.yaml
/kind feature
- enable tests with kubernetes v1.26 
- remove kubernetes version 1.22 (EOL)
- update kubernetes versions for supported releases
Fixes #
**TODOs**:
> ci: enable tests with kubernetes v1.26

- Makefile
- docker/BASEIMAGE
- docker/BASEIMAGE_CORE
/kind deprecation
- Remove `1903`, `1909` and `2004` for windows builds (EOL)
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1903-end-of-servicing
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1909-end-of-servicing
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-version-2004-end-of-servicing
Fixes #
**TODOs**:
> chore: remove windows version 1903, 1909 and 2004 (EOL)

- Makefile
- docker/Makefile
/kind feature
-  bump version to v1.3.1 in release-1.3
Fixes #
**TODOs**:
> chore: bump version to v1.3.1 in release-1.3

- Makefile
- pin buildx to `v0.10.6`
- pinning buildkit version to v0.10.6 as v0.11.0 is injecting sbom/prov to manifest causing the manifest push to fail
Fixes #
**TODOs**:
> chore: pin buildx to `v0.10.6`

- Makefile
Cherry pick of #1146 on release-1.3.
#1146: chore: pin buildx to `v0.10.6`
> Automated cherry pick of #1146: chore: pin buildx to `v0.10.6`

- cmd/secrets-store-csi-driver/main.go
- pkg/version/version.go
- pkg/version/version_test.go
/kind feature
- Adds a new `--version` flag to the driver to write the build date, git commit and version to stdout. This flag can be useful when trying to find the image tags/build details given just the digest of an image. 
Fixes #
**TODOs**:
> feat: add `--version` flag to print the driver version

- .local/debug-driver.yaml
- docker/BASEIMAGE
- docker/Dockerfile
- docs/book/src/topics/set-as-env-var.md
- docs/book/src/topics/sync-as-kubernetes-secret.md
- test/bats/tests/akeyless/pod-inline-volume-secretproviderclass.yaml
- test/bats/tests/aws/BasicTestMount.yaml
- test/bats/tests/azure/deployment-synck8s-azure.yaml
- test/bats/tests/azure/deployment-two-synck8s-azure.yaml
- test/bats/tests/azure/pod-azure-inline-volume-multiple-spc.yaml
- test/bats/tests/azure/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/azure/rotation/pod-synck8s-azure.yaml
- test/bats/tests/e2e_provider/deployment-synck8s-e2e-provider.yaml
- test/bats/tests/e2e_provider/deployment-two-synck8s-e2e-provider.yaml
- test/bats/tests/e2e_provider/pod-e2e-provider-inline-volume-multiple-spc.yaml
- test/bats/tests/e2e_provider/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/e2e_provider/rotation/pod-synck8s-e2e-provider.yaml
- test/bats/tests/gcp/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/vault/deployment-synck8s.yaml
- test/bats/tests/vault/deployment-two-synck8s.yaml
- test/bats/tests/vault/pod-vault-inline-volume-multiple-spc.yaml
- test/bats/tests/vault/pod-vault-inline-volume-secretproviderclass.yaml
- test/bats/tests/vault/pod-vault-rotation.yaml
/kind feature
- use base and test image from `registry.k8s.io`
part of https://github.com/kubernetes/k8s.io/issues/4738
**TODOs**:
> chore: use base and test image from `registry.k8s.io`

- docker/BASEIMAGE
- docker/Dockerfile
/kind cleanup
Update the base image to the latest release.
None
**TODOs**:
> chore: Update debian-base image to v1.4.3

- cmd/secrets-store-csi-driver/main.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/secrets-store/nodeserver.go
- pkg/secrets-store/nodeserver_test.go
- pkg/secrets-store/secrets-store.go
- test/sanity/sanity_test.go
/kind cleanup
The provider paths were updated to be configured in the clients in https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/851. This cleans up unused parameters that we were passing around to different components.
Fixes #
**TODOs**:
> chore: remove unused providerVolumePath code paths

- pkg/rotation/reconciler.go
/kind bug
When the reconciler errors out due to the volume name being mismatched, it returns the same error when the volume is not found. Updating the error to better reflect the actual error which is also helpful in debugging.
Fixes #
**TODOs**:
> chore: updates error message

- pkg/secrets-store/provider_client.go
- pkg/secrets-store/provider_client_test.go
- pkg/util/fileutil/writer.go
/kind cleanup
Makes WritePayloads() call Validate() internally so that it can be used safely on its own. Also cleans up some of the indentation on the provider client.
Fixes #
**TODOs**:
> chore: cleanup WritePayloads to be easier to use

- Makefile
- docker/Makefile
/kind feature
- bump version to `v1.3.3` in release-1.3
> chore: bump version to v1.3.3 in release-1.3

- pkg/rotation/reconciler_test.go
- pkg/util/secretutil/secret_test.go
/kind cleanup
More consistent use of stdlib test helpers.
Fixes #
**TODOs**:
> test: more usage of t.TempDir()

- Makefile
- docker/crd.Dockerfile
/kind cleanup
The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
Related PRs:
- https://github.com/kubernetes-sigs/image-builder/pull/656
- https://github.com/kubernetes-sigs/cluster-api/pull/4958
None.
**TODOs**:
> Use dl.k8s.io instead of hardcoded GCS URIs

- Makefile
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- config/rbac-rotation/role.yaml
- config/rbac-syncsecret/role.yaml
- config/rbac-tokenrequest/role.yaml
- config/rbac/role.yaml
- manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/charts/secrets-store-csi-driver/crds/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role-rotation.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role-syncsecret.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role-tokenrequest.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml
- manifest_staging/deploy/rbac-secretproviderclass.yaml
- manifest_staging/deploy/rbac-secretproviderrotation.yaml
- manifest_staging/deploy/rbac-secretprovidersyncing.yaml
- manifest_staging/deploy/rbac-secretprovidertokenrequest.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
A number of changes have been made directly to the manifest_staging files - but those changes get overwritten whenever we use make manifest to rebuild the files from the code annotations. This change adds a bunch of sed mutations to the output of the code generator.
Updates to the tools (which determines which version of controller-gen we use) have also not been applied.
/kind cleanup
Fixes #
**TODOs**:
> fix: make manifest diff

- docs/book/src/concepts.md
Removing unnecessary "the"
Fixing typo.
Fixes #
**TODOs**:
- [] adds unit tests
> docs: remove unnecessary "the" in concepts

- Makefile
- manifest_staging/charts/secrets-store-csi-driver/templates/role-secretproviderclasspodstatuses-viewer.yaml
- manifest_staging/deploy/role-secretproviderclasspodstatuses-viewer.yaml
- test/bats/e2e-provider.bats
This adds a new aggregated cluster role granting access to view `SecretProviderClassPodStatus`.
/kind feature
As a regular user using `SecretProviderClass`, there is currently no RBAC that allows me to view the status of SPC usage in pods. We have worked around this by asking our cluster-admin to create the aggregated clusterrole included in this PR. I think it makes sense to include this cluster role by default in an installation of Secrets Store CSI Driver.
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1281
**Special notes for your …
> helm: aggregated clusterrole to view secretproviderclasspodstatuses

- cmd/secrets-store-csi-driver/main.go
- controllers/secretproviderclasspodstatus_controller.go
- controllers/secretproviderclasspodstatus_controller_test.go
- pkg/rotation/reconciler.go
- pkg/rotation/reconciler_test.go
- pkg/util/k8sutil/volume.go
- pkg/util/k8sutil/volume_test.go
Looking through the code, the driver name seems to be configurable. However, there is one place where it is hardcoded. This PR tries to ease the restriction and allow the use of custom driver names.
/kind bug
Looking through the code, the driver name seems to be configurable. However, there is one place where it is hardcoded. This PR tries to ease the restriction and allow the use of custom driver names.
Fixes #
**TODOs**:
> fix: remove hardcoded driver name

- Makefile
- docker/Makefile
- bump version to `v1.4.0` in release-1.4
> chore: bump version to v1.4.0 in release-1.4

- docs/book/src/concepts.md
Updates security documentation.
Fixes #
**TODOs**:
> docs: updates security section

- test/scripts/run-e2e-windows.sh
Cherry pick of #1410 on release-1.4.
#1410: ci: remove low quota regions for aks windows job
> Automated cherry pick of #1410: ci: remove low quota regions for aks windows job

- test/scripts/run-e2e-windows.sh
Cluster creation in `northeurope` and `francecentral` has been flaky. I reviewed the failed jobs, and all the cluster creation failures seem to be only in these 2 regions.
> ci: remove low quota regions for aks windows job

- .local/Dockerfile
- docker/Dockerfile
- docker/windows.Dockerfile
- test/e2eprovider/Dockerfile
/kind feature
update to go 1.21.5 for docker builds
> chore: update to go 1.21.6 in docker

- .local/Dockerfile
- docker/Dockerfile
- docker/windows.Dockerfile
- test/e2eprovider/Dockerfile
Cherry pick of #1393 on release-1.4.
#1393: chore: update to go 1.21.6 in docker
> Automated cherry pick of #1393: chore: update to go 1.21.6 in docker

- docs/book/src/topics/secret-auto-rotation.md
Fixes #
**TODOs**:
**Other**
https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation
> docs: Make link to Reloader a link

- docker/BASEIMAGE
- docker/Dockerfile
/kind feature
- update debian-base to bookworm-v1.0.0
> chore: update debian-base to bookworm-v1.0.1

- docker/BASEIMAGE
- docker/Dockerfile
Cherry pick of #1457 on release-1.4.
#1457: chore: update debian-base to bookworm-v1.0.1
> Automated cherry pick of #1457: chore: update debian-base to bookworm-v1.0.1

- Makefile
- docker/Makefile
- bump version to `v1.4.2` in release-1.4
> chore: bump version to v1.4.2 in release-1.4

- docker/crd.Dockerfile
Cherry pick of #1472 on release-1.4.
#1472: security: bump kubectl to v1.29.3 in driver-crds for
> Automated cherry pick of #1472: security: bump kubectl to v1.29.3 in driver-crds for

- manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
- manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
/kind bug
Add support for more than one `linux.crds.annotations` dictionary entry in the `secrets-store-driver-csi` chart. 
Fixes # N/A
```bash
$ helm lint ./
==> Linting ./
1 chart(s) linted, 0 chart(s) failed
```
Tested by templating locally with the following configuration in values.yaml.
```
crds:
annotations:
keyOne: valueOne
keyTwo: valueTwo
```
_Before_
```bash
$ helm template .
Error: YAML parse error on secrets-store-csi-driver/templates/crds-upgrade-hook.yaml: error converting YAML to JSON: yaml: line 25: mapping …
```
> fix: support more than one linux.crds.annotations entry

- docker/BASEIMAGE
- docker/Dockerfile
/kind feature
- update debian-base to bookworm-v1.0.2
> chore: update debian-base to bookworm-v1.0.2

- docker/BASEIMAGE
- docker/Dockerfile
Cherry pick of #1491 on release-1.4.
#1491: chore: update debian-base to bookworm-v1.0.2
> Automated cherry pick of #1491: chore: update debian-base to bookworm-v1.0.2

- Makefile
- docker/Makefile
- bump version to `v1.4.3` in release-1.4
> chore: bump version to v1.4.3 in release-1.4

- docker/crd.Dockerfile
bump kubectl to v1.29.3 in driver-crds for CVE-2023-45288
> chore: bump kubectl to v1.29.4 in driver-crds for CVE-2023-45288

- Makefile
- test/bats/conjur.bats
- test/bats/tests/conjur/conjur_v1_secretproviderclass.yaml
- test/bats/tests/conjur/pod-conjur-rotation.yaml
- test/bats/tests/conjur/pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/conjur/policy/authn-jwt.yaml
- test/bats/tests/conjur/policy/host.yaml
- test/bats/tests/conjur/policy/variables.yaml
Adds e2e test retrieving secrets via [the Conjur provider](https://docs.cyberark.com/conjur-enterprise/latest/en/Content/Integrations/k8s-ocp/k8s-jwt-secrets-store-csi-driver.htm)
Fixes #
**TODOs**:
> test: add e2e for conjur csi provider

- docs/book/src/troubleshooting.md
> docs: adds troubleshooting guide for kubeletRootDir

- docker/BASEIMAGE
- docker/Dockerfile
Cherry pick of #1530 on release-1.4.
#1530: chore: update debian-base to bookworm-v1.0.3
> Automated cherry pick of #1530: chore: update debian-base to bookworm-v1.0.3

- docker/BASEIMAGE
- docker/Dockerfile
/kind feature
update debian-base to bookworm-v1.0.3
> chore: update debian-base to bookworm-v1.0.3

- docker/crd.Dockerfile
Cherry pick of #1502 on release-1.4.
#1502: chore: bump kubectl to v1.29.4 in driver-crds for
> Automated cherry pick of #1502: chore: bump kubectl to v1.29.4 in driver-crds for CVE-2023-45288

- provider/fake/fake_server.go
/kind cleanup
- Remove target path check in fake provider.
> test: remove target path check in fake provider server

- docs/book/src/concepts.md
- docs/book/src/getting-started/installation.md
- docs/book/src/introduction.md
- docs/book/src/providers.md
Adds the Conjur provider to provider lists. Followup to #1498 
N/A
**TODOs**:
> docs: Add Conjur provider

- provider/fake/fake_server.go
Cherry pick of #1543 on release-1.4.
#1543: test: remove target path check in fake provider server
> Automated cherry pick of #1543: test: remove target path check in fake provider server

- .github/workflows/create-release.yaml
`--rm-dist` is removed, using `--clean` instead.
This should resolve the `create_release` workflow failure: https://github.com/kubernetes-sigs/secrets-store-csi-driver/actions/runs/9569015004/job/26380558230
> ci: use `--clean` instead of `--rm-dist`

- .github/workflows/create-release.yaml
Cherry pick of #1555 on release-1.4.
#1555: ci: use `--clean` instead of `--rm-dist`
> Automated cherry pick of #1555: ci: use `--clean` instead of `--rm-dist`

- .github/workflows/create-release.yaml
`--debug` is removed, using `--verbose` instead.
This should resolve the `create_release` workflow failure: https://github.com/kubernetes-sigs/secrets-store-csi-driver/actions/runs/9570424010/job/26385138887
> ci: use `--verbose` instead of `--debug` in goreleaser

- .github/workflows/create-release.yaml
Cherry pick of #1557 on release-1.4.
#1557: ci: use `--verbose` instead of `--debug` in goreleaser
> Automated cherry pick of #1557: ci: use `--verbose` instead of `--debug` in goreleaser

- test/bats/azure.bats
- test/scripts/e2e_provider.sh
- Use e2e-provider for manifest tests
This enables us to move to eks prow cluster without any dependencies on secrets used by the azure provider.
> test: use e2e-provider for manifest tests

- test/bats/azure.bats
Cherry pick of #1597 on release-1.4.
#1597: bump kubectl version to v1.30.2
> Automated cherry pick of #1597: bump kubectl version to v1.30.2

- test/bats/e2e-provider.bats
Cherry pick of #1585 on release-1.4.
#1585: test: reset rotation response in mock server for upgrade
> Automated cherry pick of #1585: test: reset rotation response in mock server for upgrade

- Makefile
- docker/Makefile
bump version to `v1.4.5` in release-1.4
> chore: bump version to v1.4.5 in release-1.4

- .github/workflows/create-release.yaml
Set version to `v2` for goreleaser (xref: https://goreleaser.com/blog/goreleaser-v2/#github-action)
> ci: use v2 for goreleaser

- .github/workflows/create-release.yaml
- .goreleaser.yml
Validation before the change:
```bash
➜ goreleaser check        
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
⨯ command failed                                   error=only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
```
Validation after the change:
```bash
➜ goreleaser check
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
> ci: update goreleaser config for v2

- docker/BASEIMAGE
- docker/Dockerfile
Cherry pick of #1660 on release-1.4.
#1660: chore: bumps base images
> Automated cherry pick of #1660: chore: bumps base images

- Makefile
- docker/Makefile
bump version to v1.4.6 in release-1.4
> chore: bumps version for v1.4.6 release

- test/bats/gcp.bats
- test/scripts/run-e2e-gcp.sh
**What this PR does / why we need it**: Runs e2e test for driver with gcp provider
Fixes #1583
Earlier gcp tests were using hardcoded static secrets from google owned project. Now this PR uses secrets freshly created on boskos project.
**TODOs**:
> test: add e2e test setup for GCP provider

- OWNERS
Move @tam7t to `emeritus_approvers`. Thank you for all the work on the project!
> chore: move tam7t to emeritus_approvers

- pkg/util/secretutil/secret.go
- pkg/util/secretutil/secret_test.go
/kind bug
Fix the hash generation logic to prevent hash collision with different maps as input. This can be caused because of the concatenation logic.
The test added in https://github.com/kubernetes-sigs/secrets-store-csi-driver/commit/b94492d3eeda05e1589e1f4880ef2a5bb02f35a0 shows the bug in the current logic.
```bash
=== RUN   TestGenerateSHAFromSecret/different_keys_with_the_same_concatenated_result_but_should_not_match
secret_test.go:434: 
Error Trace:	/Users/anishramasekar/go/src/sigs.k8s.io/secrets-store-csi-driver/pkg/util/secretutil/secret_test.go:434
Error:      	Not equal: 
expected: false
actual  : true
Test:       	TestGenerateSHAFromSecret/different_keys_with_the_same_concatenated_result_but_should_not_match
--- FAIL: …
```
> fix: update the hash generation logic

- docker/Dockerfile
- docker/windows.Dockerfile
- go.mod
- test/e2eprovider/Dockerfile
- test/e2eprovider/go.mod
fixes image scan failures: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-secrets-store-csi-driver-image-scan/1910943843440660480
> security: bump to go 1.23.8 to resolve CVE-2025-22871

- OWNERS
/kind cleanup
/triage accepted
/assign enj
> chore: move nilekhc to emeritus_reviewers

- .github/dependabot.yml
I'm explicitly configuring it to use the same label that Dependabot applies by default. If a custom label is specified in the config, Dependabot doesn't add the default labels.
(xref: https://github.com/kubernetes/release/blob/b28854edebcb345c31260b53510368725225b079/.github/dependabot.yml#L8) for other places we do this.
> ci: add area/dependency label for dependabot PRs

- docker/Dockerfile
- docker/windows.Dockerfile
- go.mod
- test/e2eprovider/Dockerfile
- test/e2eprovider/go.mod
Cherry pick of #1819 on release-1.5.
#1819: chore: update to go 1.23.9
> chore: update to go 1.23.9

- docker/BASEIMAGE
- docker/Dockerfile
Cherry pick of #1853 on release-1.5.
#1853: chore: update debian-base to bookworm-v1.0.5
> chore: update debian-base to bookworm-v1.0.5

- docker/BASEIMAGE
- docker/Dockerfile
- docker/crd.Dockerfile
- docker/windows.Dockerfile
- go.mod
- hack/tools/go.mod
- test/e2eprovider/Dockerfile
- test/e2eprovider/go.mod
/kind cleanup
/triage accepted
> chore: update to go 1.24.7 and bump base image 

- docker/BASEIMAGE
- docker/Dockerfile
- docker/crd.Dockerfile
- docker/windows.Dockerfile
- go.mod
- hack/tools/go.mod
- test/e2eprovider/Dockerfile
- test/e2eprovider/go.mod
Cherry pick of #1915 on release-1.5.
#1915: chore: update to go 1.24.7
> chore: update to go 1.24.7 and bump base image
