kubernetes-sigs/secrets-store-csi-driver

Makefile
README.md
deploy/example/nginx-pod-keyvault-deployment.yaml
deploy/example/nginx-pod-keyvault.yaml
deploy/keyvault-csi-driver.yaml
pkg/keyvault/keyvault.go
pkg/keyvault/nodeserver.go
pkg/providers/azure/provider.go

- make volume readonly
- validate required fields and return error to user
- add deployment example with replicas
fixes #3 #6

Add validation for required fields

---

pkg/keyvault/nodeserver.go

fix issues with unmount

---

Makefile
README.md
charts/secrets-store-csi-driver/Chart.yaml
charts/secrets-store-csi-driver/templates/csidriver.yaml
charts/secrets-store-csi-driver/values.yaml
deploy/csidriver.yaml
deploy/secrets-store-csi-driver.yaml
pkg/csi-common/driver.go
pkg/providers/azure/provider.go
pkg/secrets-store-csi-driver/main.go
pkg/secrets-store/nodeserver.go
pkg/secrets-store/secrets-store.go

[Azure] integrate with pod identity

---

pkg/secrets-store/nodeserver.go

should not check for secret until inside of a provider

fix nil secret

---

pkg/providers/azure/provider.go

- Fixes error check when getting management token. The error that's used in `errors.Wrap` is always nil because it's the wrong var.
- Fix lint errors in `provider/azure`

Fix error check when failed to get token

---

pkg/providers/vault/docs/vault-setup.md
pkg/providers/vault/provider.go
pkg/secrets-store/nodeserver.go

Fix bad url, panic for vault provider

---

pkg/secrets-store/nodeserver.go

Fixes https://github.com/deislabs/secrets-store-csi-driver/issues/61

Handle case sensitive provider name check

---

charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
deploy/secrets-store-csi-driver.yaml

Fixes https://github.com/deislabs/secrets-store-csi-driver/issues/63

Use node-driver-registrar sidecar

---

pkg/providers/azure/README.md

- Update Hashicorp Vault demo gif to include the latest
- Update Azure Key Vault provider readme

Update provider README

---

pkg/providers/azure/README.md
pkg/providers/azure/examples/nginx-pod-secrets-store-inline-volume-pod-identity.yaml
pkg/providers/azure/examples/nginx-pod-secrets-store-inline-volume.yaml
pkg/providers/azure/examples/pv-secrets-store-csi.yaml
pkg/providers/azure/examples/v1alpha1_secretproviderclass.yaml
pkg/providers/azure/examples/v1alpha1_secretproviderclass_podid.yaml
pkg/providers/azure/provider.go

- Adds ability to configure cloud name in attributes
- Updates docs and examples with `cloudName` attribute
Fixes https://github.com/deislabs/secrets-store-csi-driver/issues/80

option to set cloud name for azure provider

---

README.md

Add Helm installation example without Tiller
Tiller might be a security concern.

Add Helm installation example without Tiller

---

pkg/secrets-store/nodeserver.go

Update mount tmpfs

---

pkg/csi-common/utils.go

Redact all secrets

---

pkg/secrets-store/nodeserver.go

Fixes https://github.com/deislabs/secrets-store-csi-driver/issues/107

validate read-only mode

---

pkg/secrets-store/nodeserver.go

Validate args before mount

---

.gitignore
cmd/secrets-store-csi-driver/main.go
go.mod
pkg/secrets-store/controllerserver.go
pkg/secrets-store/nodeserver.go
pkg/secrets-store/secrets-store.go
test/sanity/sanity_test.go

feat: make volume path for provider a flag

---

charts/secrets-store-csi-driver/values.yaml
deploy/provider-azure.yaml

Fixes https://github.com/deislabs/secrets-store-csi-driver/issues/86

update to official provider-azure image

---

charts/secrets-store-csi-driver/templates/azure-provider.yaml
charts/secrets-store-csi-driver/templates/vault-provider.yaml
deploy/provider-azure.yaml
deploy/provider-vault.yaml

Update `apiVersion` for provider manifests and charts.

update manifest api versions for providers

---

charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
charts/secrets-store-csi-driver/values.yaml
go.mod
pkg/secrets-store/identityserver.go
pkg/secrets-store/identityserver_test.go
pkg/secrets-store/secrets-store.go
pkg/secrets-store/secrets-store_test.go

fixes https://github.com/deislabs/secrets-store-csi-driver/issues/119

Add liveness probe

---

charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
secretProviderClass/config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
test/bats/vault.bats

Add categories for crd

---

charts/secrets-store-csi-driver/templates/csidriver.yaml

Update for use with Kubernetes 1.16.

---

README.md
charts/secrets-store-csi-driver/templates/csidriver.yaml
charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
cmd/secrets-store-csi-driver/main.go
deploy/csidriver-1.15.yaml
deploy/csidriver.yaml
deploy/secrets-store-csi-driver.yaml
test/bats/tests/nginx-pod-secrets-store-inline-volume-crd.yaml
test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
test/bats/tests/nginx-pod-vault-inline-volume-secretproviderclass.yaml
test/sanity/sanity_test.go

Update driver name to k8s.io

---

README.md

- adding build badge that reflects results for e2e runs from master
/assign @ritazh 
cc @craiglpeters

add build badge based on postsubmit

---

pkg/secrets-store/nodeserver.go

- return early if provider is `mock_provider`. This helps us move the large code block out of the else loop
- Adds comment about mounting `tmpfs` in case of `linux` and `windows`
Fixes #

return early if mock provider and add mnt comments

---

Makefile

Bumps image version to v0.0.10 in preparation for next release.
Fixes #

bump version to v0.0.10

---

README.md
test/bats/azure.bats
test/bats/tests/azure_synck8s_v1alpha1_secretproviderclass.yaml

Update doc, test to sync alias

---

README.md

chore: add slack channel for csi-secrets-store

---

Makefile
pkg/secrets-store/secrets-store.go

chore: bump version to v0.0.11

---

test/bats/azure.bats

test: update azure key tests for latest release 0.0.6

---

docker/Makefile

set DOCKER_CLI_EXPERIMENTAL in makefile

---

docker/cloudbuild.yaml

set gcr_cloud_build for buildx

---

docker/build.sh

manifest-tool has some issues handling gcr.io credentials. We were using manifest-tool in order to create the manifest list, especially for its ability to also add information regarding the Windows images' OS version.
Alternatively, we can simply amend the manifests created by docker manifest instead.
Fixes #
/cc @aramase 
Manifest: https://paste.ubuntu.com/p/Vtp6jSp2Ft/

image: Switch from manifest-tool to docker manifest

---

README.md

doc: add note about community call

---

README.md

Removed specific meeting info so that everything is contained in the meeting agenda/notes doc so we don't have to update this all the time.
Fixes #

Update community meeting

---

go.mod
pkg/csi-common/utils.go

Add stripping sensitive information while logging the grpc request.
Fixes #144 

Add stripping sensitive information while logging the grpc request

---

README.md

Adds these 3 badges to readme
[![Go Report Card](https://goreportcard.com/badge/kubernetes-sigs/secrets-store-csi-driver)](https://goreportcard.com/report/kubernetes-sigs/secrets-store-csi-driver)
Fixes #

doc: add release, go report, go version badge

---

apis/v1alpha1/secretproviderclass_types.go
config/crd/bases/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
controllers/secretproviderclasspodstatus_controller.go
controllers/secretproviderclasspodstatus_controller_test.go
manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
manifest_staging/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
test/bats/azure.bats
test/bats/tests/azure/azure_synck8s_v1alpha1_secretproviderclass.yaml
test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml
test/bats/vault.bats

There was an ask to support label in synced secrets
Fixes #217 

feat: add `metadata.label` to synced secret

---

README.md
docs/README.limitations.md

- Adds known limitations docs
fixes #290, fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/231

docs: add known limitations docs

---

README.md
docs/README.new-provider.md

- Adds a doc for implementing new provider with `gRPC`
Fixes #

docs: add doc for new provider gRPC

---

controllers/secretproviderclasspodstatus_controller.go
pkg/rotation/reconciler.go
pkg/util/secretutil/secret.go
pkg/util/secretutil/secret_test.go

- Add `strings.TrimSpace` for all fields obtained as string from manifests
- Adds positive test cases for `GetSecretData`
Fixes #

feat: add trimspace to sanitize yaml fields

---

Makefile
cmd/secrets-store-csi-driver/main.go
pkg/secrets-store/secrets-store.go
test/bats/azure.bats
test/bats/tests/azure/nginx-deployment-synck8s-azure.yaml
test/bats/tests/azure/nginx-deployment-two-synck8s-azure.yaml
test/bats/tests/azure/nginx-pod-azure-inline-volume-multiple-spc.yaml
test/bats/tests/azure/rotation/azure_synck8s_v1alpha1_secretproviderclass.yaml
test/bats/tests/azure/rotation/nginx-pod-synck8s-azure.yaml
test/bats/tests/vault/nginx-deployment-synck8s.yaml
test/bats/tests/vault/nginx-deployment-two-synck8s.yaml
test/bats/tests/vault/nginx-pod-vault-inline-volume-multiple-spc.yaml

- Adds e2e tests for auto rotation with azure provider
Fixes #

test: add e2e tests for rotation with azure provider

---

README.md
docs/README.metrics.md
docs/README.rotation.md

docs: add doc for auto rotation

---

README.md

Link to GCP provider now that integration tests have been added.
Fixes #

readme: add link to GCP provider

---

README.md

docs: add mailing list url to readme

---

sample/ingress-controller-tls/README.md

docs: update doc link for azure tls sample

---

OWNERS

Thank you for all the contributions so far @tam7t! 
Fixes #
The criteria for membership is documented in [Secrets Store CSI Driver Membership](https://docs.google.com/document/d/1YqFVTJdxvNXhXkWogYf7AOKMnUjPFHCPuYtTgJSHohU/edit?usp=sharing)

add tam7t as reviewer

---

README.md

docs: update install doc for crds to check

---

Makefile

This is a workaround until the bug is fixed in buildkit: https://github.com/moby/buildkit/pull/1879
Fixes #

fix: windows image build with buildx

---

.github/PULL_REQUEST_TEMPLATE.md

docs: update PR template for chart updates

---

Makefile
docker/Dockerfile
docker/Makefile

fix: CVE-2020-27350, CVE-2020-29362

---

manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
manifest_staging/deploy/secrets-store-csi-driver.yaml

chore: remove host network

---

docker/BASEIMAGE
docker/BASEIMAGE_CORE

feat: enable 2004 builds for windows images

---

sample/ingress-controller-tls/README.md

docs: update ingress sample url for azure provider

---

Makefile
docker/Dockerfile
docker/Makefile

fix: CVE-2021-24032

---

Makefile

- Add Makefile target to deploy helm chart release. This will be used when we cut a release.
Fixes #

test: add make target for installing chart releases

---

Makefile

Adds `e2e-helm-deploy` for windows tests
Fixes #

ci: add helm deploy target for windows tests

---

docs/book/src/load-tests.md

- Fixes indentation in load tests doc
Fixes #

docs: fix indentation in load tests

---

test/README.md

- Add documentation for current tested scenarios + providers
Fixes #501

docs: add test scenarios currently supported

---

pkg/util/fileutil/filesystem.go
pkg/util/fileutil/filesystem_test.go

This PR fixes Secret is not created when ObjectName has a directory path.
**Which issue(s) this PR fixes**
fixes #515 

fix: GetMountedFiles() returns map that key includes sub directory

---

Makefile
test/bats/aws.bats
test/bats/tests/aws/BasicTestMount.yaml
test/bats/tests/aws/BasicTestMountSPC.yaml
test/scripts/initialize_eks_cluster.bash

add aws integration tests

---

OWNERS

Thank you for all the contributions so far @tam7t! 
Fixes #
The criteria for membership is documented in [Secrets Store CSI Driver Membership](https://docs.google.com/document/d/1YqFVTJdxvNXhXkWogYf7AOKMnUjPFHCPuYtTgJSHohU/edit?usp=sharing)

add tam7t as approver

---

docs/RELEASE.md

Needed for kubernetes/k8s.io#1597
Needed for kubernetes/k8s.io#1597

master to main rename

---

go.mod
pkg/secrets-store/nodeserver.go
pkg/secrets-store/nodeserver_test.go
test/e2eprovider/server.go
test/e2eprovider/server_test.go

This PR is an initial implementation for supporting Token Request. 
Fixes #453
This is an initial attempt at adding token request support. If this is the wrong approach, feel free to close it and we can iterate on the design before making a PR. I haven't yet tried making a minimal provider that can support token request yet, but will hopefully have something to test with in the next week or two.

Initial implementation of token request

---

test/bats/helpers.bash

**What this PR does / why we need it**: Improve debug visibility
Fixes #

tests: include more debug info in artifacts

---

README.md

**What this PR does / why we need it**: elevate test status visibility for non-PR tests
Fixes #

docs: use testgrid for readme test status

---

docker/build.sh

fix: add ARCH build arg for driver-crds

---

manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
test/bats/azure.bats

Cherry pick of #656 on release-0.1.
#656: feat: add keep-crd upgrade hook

Automated cherry pick of #656: feat: add keep-crd upgrade hook

---

docs/book/src/getting-started/upgrades.md

docs: add details on v0.1.0 upgrades

---

docs/MEMBERSHIP.md

Signed-off-by: Karen Chu <karen.chu@microsoft.com>
Fixes #

Update Membership.md with more roles/details

---

test/scripts/initialize_eks_cluster.bash

RELEASE=true is a signal from prow that we are running release tests
which exercise the charts/ folder at release time.
**What this PR does / why we need it**: compliment to https://github.com/kubernetes/test-infra/pull/22908
Addresses https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/592

tests: aws support for RELEASE tests

---

docs/Release_Management.md

Match branch naming style
Fixes #

docs: Update Release_Management.md

---

docker/Dockerfile
docker/crd.Dockerfile
docker/windows.Dockerfile
pkg/metrics/exporter.go
pkg/metrics/prometheus_exporter.go
pkg/rotation/stats_reporter.go
pkg/secrets-store/mocks/stats_reporter_mock.go
pkg/secrets-store/stats_reporter.go
pkg/util/fileutil/atomic_writer.go
pkg/util/fileutil/writer.go
pkg/version/version.go
pkg/version/version_test.go
test/e2eprovider/Dockerfile
test/e2eprovider/e2e_provider.go
test/e2eprovider/server/server.go
test/e2eprovider/server/server_test.go
test/e2eprovider/types/types.go
test/sanity/sanity_test.go
test/scripts/e2e_provider.sh
test/scripts/initialize_eks_cluster.bash

- Adds LICENSE to all the files
Fixes #

chore: add LICENSE to all files

---

docs/design/README.md

- Updates the design doc status
- Adds new design docs to the roadmap
Fixes #

docs: update design docs status

---

test/bats/e2e-provider.bats

This PR adds support for inplace upgrade test with e2e-provider
Fixes #739 

feat: adds support for inplace upgrade test

---

test/bats/e2e-provider.bats
test/e2eprovider/server/server.go
test/scripts/e2e_provider.sh

Fixes inplace upgrade tests
Fixes #746

fix: inplace upgrade test

---

docs/book/src/providers.md

This PR documents Secret Store CSI provider's features support matrix.
Fixes #333 

docs: providers support matrix

---

docker/BASEIMAGE

fix: update base image core for ltsc2022

---

docker/cloudbuild.yaml

Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523

images: use k8s-staging-test-infra/gcb-docker-gcloud

---

Makefile
README.md

docs: add slack badge

---

Makefile
README.md

Cherry pick of #822 on release-1.0.
#822: docs: add slack badge

Automated cherry pick of #822: docs: add slack badge

---

Makefile

Updates trivy command to avoid breaking change.
https://github.com/aquasecurity/trivy/discussions/1515
Fixes #

chore: updates trivy command

---

docs/book/src/getting-started/installation.md
manifest_staging/charts/secrets-store-csi-driver/README.md

docs: remove helm repo url change note in install steps

---

Makefile

- `shellcheck */*.sh` doesn't check all the shell files in the repo. Changing to use `find` all files and then run shellcheck.
```bash
➜ make shellcheck
mkdir -p /home/anramase/go/src/sigs.k8s.io/secrets-store-csi-driver/hack/tools/bin
rm -rf "/home/anramase/go/src/sigs.k8s.io/secrets-store-csi-driver/hack/tools/bin/shellcheck-v0.7.2*"
curl -sfOL "https://github.com/koalaman/shellcheck/releases/download/v0.7.2/shellcheck-v0.7.2.linux.x86_64.tar.xz"
tar xf shellcheck-v0.7.2.linux.x86_64.tar.xz
cp "shellcheck-v0.7.2/shellcheck" "/home/anramase/go/src/sigs.k8s.io/secrets-store-csi-driver/hack/tools/bin/shellcheck-v0.7.2"
ln -sf "/home/anramase/go/src/sigs.k8s.io/secrets-store-csi-driver/hack/too …
```

ci: fix shellcheck file paths

---

pkg/secrets-store/nodeserver.go
pkg/secrets-store/nodeserver_test.go

Cherry pick of #873 on release-1.1.
#873: fix: add unit test to validate error shadowed bug

Automated cherry pick of #873: fix: add unit test to validate error shadowed bug

---

docs/book/src/concepts.md
docs/book/src/introduction.md
docs/book/src/topics/set-as-env-var.md

docs: update supported versions and replace v1alpha1 with v1

---

docs/book/src/known-limitations.md

- Validated when `subPath` volume mount is used, the container does not receive the rotated secret. Adding this to known limitations.
Fixes #680 

docs: add subPath volume mount limitation

---

Makefile

chore: upgrade makefile test binary versions

---

Makefile
docker/Makefile

steps 4/5 of https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/RELEASE.md
Fixes #

chore: bump version 1.1.2

---

test/bats/azure.bats

test: use helm charts for azure provider

---

docs/book/src/concepts.md

Also addresses issues around accidental persistence of secret material
to disks #707 (document swap) and #763 (windows).
Fixes #707, Fixes #763

docs: include security explanations for root/privileged/and pod tokens

---

OWNERS

Thank you for all the contributions so far @nilekhc! 
Fixes #
**TODOs**:

add nilekhc to reviewers

---

pkg/secrets-store/nodeserver.go

/kind bug
For windows, we remove all the files in the mount prior to calling `CleanupMountPoint`. This is because the files are just written to the node's filesystem. `CleanupMountPoint` essentially deletes the directory. In case of Linux, `CleanupMountPoint` will unmount and then delete the directory. As reported in #936, the files are still in the mount that cause deletion of the target path to fail. With this PR to ensure the unpublish volume always succeeds, we're deleting the files first for Linux and Windows before calling `CleanupMountPoint`.
**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

fix: remove files before cleanup mount point in unpublish

---

docs/book/src/getting-started/installation.md
docs/book/src/introduction.md

- Updates supported releases in the doc
- Adds instructions for deploying token request rbac role if required
Fixes #
**TODOs**:

docs: update supported releases - v1.2.x and v1.1.x

---

docker/Dockerfile

/kind bug
```shell
gcr.io/k8s-staging-csi-secrets-store/driver:v1.2.0-e2e-9a4d7f4e (debian 11.4)
Total: 2 (MEDIUM: 0, HIGH: 2, CRITICAL: 0)
┌─────────────────┬────────────────┬──────────┬───────────────────┬─────────────────┬──────────────────────────────────────────────────────┐
│     Library     │ Vulnerability  │ Severity │ Installed Version │  Fixed Version  │                        Title                         │
├─────────────────┼────────────────┼──────────┼───────────────────┼─────────────────┼──────────────────────────────────────────────────────┤
│ libtirpc-common │ …
```

security: fix multiple CVEs

---

Makefile
docker/Makefile

/kind feature
Fixes #
**TODOs**:

chore: bump version to v1.2.3 in release-1.2

---

Makefile
docker/BASEIMAGE
docker/Makefile

/king bug
- Updates the base image reference in the build file used for scripts.
Fixes #
**TODOs**:

fix: update base image reference in script

---

docker/Dockerfile

/kind bug
```shell
┌─────────┬────────────────┬──────────┬─────────────────────────┬─────────────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │    Installed Version    │      Fixed Version      │                           Title                           │
├─────────┼────────────────┼──────────┼─────────────────────────┼─────────────────────────┼───────────────────────────────────────────────────────────┤
│ zlib1g  │ CVE-2022-37434 │ CRITICAL │ 1:1.2.11.dfsg-2+deb11u1 │ 1:1.2.11.dfsg-2+deb11u2 │ zlib: a heap-based buffer over-read or buffer overflow in │
│         │                │          │ …
```

security: fix CVE-2022-37434

---

manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml
manifest_staging/charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml
manifest_staging/charts/secrets-store-csi-driver/templates/role.yaml

/kind cleanup
- Remove psp
Fixes #
**TODOs**:

chore: remove psp

---

Makefile
docker/Makefile

/kind feature
Fixes #
**TODOs**:

chore: bump version to v1.2.4 in release-1.2

---

.markdownlinkcheck.json

-  ignore slack badge in markdown link check as it's returning 404 in workflow
Fixes #
**TODOs**:

ci: ignore slack badge in markdown link check

---

docs/book/src/concepts.md

docs: fix typo in concepts doc

---

docs/book/src/introduction.md

- update supported releases - v1.3.x and v1.2.x
Fixes #
**TODOs**:

docs: update supported releases - v1.3.x and v1.2.x

---

Makefile
docker/Makefile

/kind feature
- bump version to v1.3.2 in release-1.3
Fixes #
**TODOs**:

chore: bump version to v1.3.2 in release-1.3

---

pkg/secrets-store/nodeserver.go

/kind bug
fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1208

fix: update nodeserver publish logs

---

.golangci.yml
docker/Dockerfile
docker/windows.Dockerfile
test/e2eprovider/Dockerfile

/kind feature
- update to go 1.20

chore: update to go 1.20

---

manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml
manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml

/kind cleanup
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1205
**TODOs**:

chore: allow retries on pre-upgrade hook jobs

---

.github/workflows/e2e.yaml

/kind cleanup
- update kubernetes versions for staging image tests

ci: update kubernetes versions for staging image tests

---

.github/workflows/codecov.yaml
.gitignore
Makefile
codecov.yml

/kind feature
- add codecov workflow

ci: add codecov.yml

---

.github/dependabot.yml
.github/workflows/chart.yaml
.github/workflows/codecov.yaml
.github/workflows/codeql.yaml
.github/workflows/create-release.yaml
.github/workflows/dependency-review.yaml
.github/workflows/e2e.yaml
.github/workflows/markdown-link-check.yaml
.github/workflows/scorecards.yaml
.local/Dockerfile
docker/Dockerfile
test/e2eprovider/Dockerfile

/kind feature
creating this in place of https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1230 as the `step-security-bot` doesn't have CLA.

ci: [StepSecurity] Apply security best practices

---

pkg/secrets-store/nodeserver_test.go

/kind cleanup
Cleanup some variable names in tests and split success/failure into separate test cases when it seems like the expectation logic should be different
(https://github.com/golang/go/wiki/TestComments#table-driven-tests-vs-multiple-test-functions).
I also updated this to use a mock provider grpc server like we use in the rotation reconciler.
Fixes #
**TODOs**:

test: improve nodeserver testing

---

docker/BASEIMAGE
docker/Dockerfile

/kind feature
- update debian-base to bookworm-v1.0.0

chore: update debian-base to bookworm-v1.0.0

---

README.md

- mention sig-auth subproject in readme

docs: mention sig-auth subproject in readme

---

docs/book/src/providers.md

AWS provider has a Helm chart, updating the docs accordingly.
Fixes #
**TODOs**:
- [ x ] squashed commits
- [ x ] includes documentation
- [ NA ] adds unit tests

docs: update matrix for aws provider helm chart

---

docs/book/src/introduction.md

- update supported releases - v1.3.x and v1.4.x

docs: update supported releases - v1.3.x and v1.4.x

---

docs/book/src/concepts.md
docs/book/src/getting-started/installation.md
docs/book/src/getting-started/usage.md
docs/book/src/introduction.md
docs/book/src/providers.md

docs: add Akeyless to supported providers

---

docs/book/src/topics/best-practices.md

Add clarity to mount action in best-practices.md
Clarifies the statement on ability.

docs: Add clarity to mount action in best-practices.md

---

Makefile
docker/Makefile

/kind feature
bump version to v1.4.4 in release-1.4

chore: bump version to v1.4.4 in release-1.4

---

docs/book/src/providers.md

documentation
just updated that Akeyless enables rotation according to https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation
Fixes #
**TODOs**:

Akeyless now provides Rotation

---

manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver-windows.yaml
manifest_staging/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml

/kind feature
Fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1539
**TODOs**:

feat: handles sha string in tag

---

test/bats/e2e-provider.bats

- reset rotation response in mock server for upgrade tests

test: reset rotation response in mock server for upgrade tests

---

.goreleaser.yml

```bash
➜ goreleaser check        
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```

ci: skip builds goreleaser config

---

cmd/secrets-store-csi-driver/main.go

refactor: cleanup unused err check

---

.goreleaser.yml

Includes changes from `main` to fix goreleaser workflow.
/assign @nilekhc

ci: update goreleaser config for v2

---

Makefile

The new [Secrets Store Sync Controller](https://github.com/kubernetes-sigs/secrets-store-sync-controller/blob/main/Makefile#L81) has a nice output when `make help` (or bare `make`) is run.  This PR just borrows the `.PHONY: help` incantation then reformats the headings and comments on [some] commands to match the regex in the `@awk` to print the following:
This is a quick pass to get some headings and commands and text printed.  The specific output combo of headings/commands/text is up for conversation and feedback.
I would consider this: 
/kind documentation 
See above comment and screenshot.
**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

chore: Add help to makefile

---

test/e2eprovider/e2e_provider.go

Fix typo in e2d_provider.go
Fixes #
**TODOs**:

chore: fix typo in e2e_provider.go

---

docker/Dockerfile
docker/windows.Dockerfile
go.mod
test/e2eprovider/Dockerfile
test/e2eprovider/go.mod

chore: update to go 1.23.9

---

test/scripts/run-e2e-azure.sh

Switch to using Azure RBAC for keyvault permissions.

ci: update azure scripts to use rbac for keyvault permissions

---

test/scripts/run-e2e-azure.sh

Cherry pick of #1929 on release-1.5.
#1929: ci: resolve azure e2e test flakes with rbac, windows vm size

ci: resolve azure e2e test flakes with rbac, windows vm size

---

Makefile
docker/Makefile

chore: bump version to v1.5.4 in release-1.5
